function malloc_8bit(len) {
  return new Uint8Array(len);
}
function base64ToBuffer(base64) {
  var binstr = atob(base64);
  var buf = new Uint8Array(binstr.length);
  Array.prototype.forEach.call(binstr, function(ch, i) {
    buf[i] = ch.charCodeAt(0);
  });
  return buf;
}
function bufferToBase64(buf) {
  var binstr = Array.prototype.map
                   .call(
                       buf,
                       function(ch) {
                         return String.fromCharCode(ch);
                       })
                   .join('');
  return btoa(binstr);
}
// AABrAQAAxmlzUf9K7CnNuqvy++NGfMJU+Bvo5412Wi5jM5/JmmYyDbcxWKNaJV0FF1jpXtSrss3Gm7RUEQ6CdEEhPdyHcOk+oUHh/Gc+AX6X6txrlo84XCrssDv7Mq88VOwY21wCGv5D+/qqOvsp0eYFPHyUddi+YYn5XLuomQ+VsevxswXv9wDpoTrlygvL0EhHZL0fIx6oHHtkxRRzWsVeS3ljO3BkJBGeCdyq1KzyGxCvOzPN41BIRxVcu28iGbqbffUL4RocfyP4KfikGxO1yk7omDI44HlNPTS8X053+stsBayGISuqGlWivnC1czsEXNM2lLOv4vDknk8yFUn9gk6pCHDUsoopVEiaCrzVDhioRKxb845M1y2bCULlBsQzr82jhH8trdR2R94yHOxKxDD2ICOFbPuyBwT07Au5ILqGwz4F8ezZZzO3mVCj4xTT2TT3XqDyEKj2BZQBvrS8RHj6SWnmI9Aa2mmCaXNR7krsKc2JrfK/5UZbxFS9HejvjXZaLkMzn8GaZjIN/zdYuVolXQU5Xulx0quVy8a2slQ2CII1RyEF2od16T6hJdxpc1H6SuwpzKur8vvhRnzDVPob6eeOdl4u


function copyBufferToHeap(u8buffer) {
  ptr = Module._malloc(u8buffer.length);
  Module.HEAPU8.set(u8buffer, ptr);
  return ptr;
}
function freeHeap(ptr) {
  Module._free(ptr);
}
var msdreader = {
  deleteBookPosIndicator:
      Module.cwrap('deleteBookPosIndicator', 'number', ['number']),
  getBookFromBuf:
      Module.cwrap('getBookFromBuf', 'number', ['number', 'number']),
  getBookGroupsCount: Module.cwrap('getBookGroupsCount', 'number', ['number']),
  getBookAtomsCount: Module.cwrap('getBookAtomsCount', 'number', ['number']),
  getRendererFormat: Module.cwrap(
      'getRendererFormat', 'number',
      ['number', 'number', 'number', 'number', 'number', 'number', 'number']),
  getBookRenderer: Module.cwrap(
      'getBookRenderer', 'number', ['number', 'number', 'number', 'number']),
  getRendererFormatTextColor:
      Module.cwrap('getRendererFormatTextColor', 'number', ['number']),
  getImageofPageResult:
      Module.cwrap('getImageofPageResult', 'number', ['number']),
  renderNextPage:
      Module.cwrap('renderNextPage', 'number', ['number', 'number']),
  renderBackPage:
      Module.cwrap('renderBackPage', 'number', ['number', 'number']),

  getIndicatorPart:
      Module.cwrap('getIndicatorPart', 'number', ['number', 'number']),
  initBookIndicator: Module.cwrap('initBookIndicator', 'number', []),
  BookNextPart: Module.cwrap('BookNextPart', 'number', ['number', 'number']),
  getFontBuffer: Module.cwrap('getFontBuffer', 'number', ['number']),
  getFontBufferLen: Module.cwrap('getFontBufferLen', 'number', ['number']),
  getBookIndicatorPartOfPageResult:
      Module.cwrap('getBookIndicatorPartOfPageResult', 'number', ['number']),
  is_last_atom: Module.cwrap('is_last_atom', 'number', ['number', 'number']),
  is_first_atom: Module.cwrap('is_first_atom', 'number', ['number', 'number']),
  getBookType: Module.cwrap('getBookType', 'number', ['number']),
  deleteRenderedPage: Module.cwrap('deleteRenderedPage', 'number', ['number']),
  deleteBytePoniter: Module.cwrap('deleteBytePoniter', 'number', ['number']),
  getBookTotalAtoms: Module.cwrap('getBookTotalAtoms', 'number', ['number']),
  getBookProgress: Module.cwrap('getBookProgress', 'number', ['number']),
  gotoBookPosIndicator:
      Module.cwrap('gotoBookPosIndicator', 'number', ['number', 'number']),
  getBookPosIndicators:
      Module.cwrap('getBookPosIndicators', 'number', ['number']),
  getBookContentAt:
      Module.cwrap('getBookContentAt', 'number', ['number', 'number']),
  getBookContentLength:
      Module.cwrap('getBookContentLength', 'number', ['number']),
  renderNextPages:
      Module.cwrap('renderNextPages', 'number', ['number', 'number', 'number']),
  getBookPlayer: Module.cwrap('getBookPlayer', 'number', ['number']),
  getVoiceDuration: Module.cwrap(
      'getVoiceDuration', 'number', ['number', 'number', 'number']),
  deleteBookPlayer: Module.cwrap('deleteBookPlayer', 'number', ['number']),
  getVoiceAtomWrapper:
      Module.cwrap('getVoiceAtomWrapper', 'number', ['number', 'number']),
  deleteVoiceAtomWrapper:
      Module.cwrap('deleteVoiceAtomWrapper', 'number', ['number']),
  getVoiceSampleRate: Module.cwrap('getVoiceSampleRate', 'number', ['number']),
  getVoiceChannelsCount:
      Module.cwrap('getVoiceChannelsCount', 'number', ['number']),
  get10Seconds: Module.cwrap('get10Seconds', 'number', ['number', 'number']),
  getFirstAtom: Module.cwrap('getFirstAtom', 'number', ['number']),
  getLastAtom: Module.cwrap('getLastAtom', 'number', ['number']),
  getVoiceAtomWrapperDuration: Module.cwrap('getVoiceAtomWrapperDuration','number',['number'])

}

function color(r, g, b, a) {
  rtn = r;
  rtn = (rtn << 8) + g;
  rtn = (rtn << 8) + b;
  rtn = (rtn << 8) + a;
  return rtn;
} function deserialize_book(b64str) {
  bookbuf = base64ToBuffer(b64str);
  bookbufptr = copyBufferToHeap(bookbuf);
  bookptr = getBookFromBuf(bookbufptr, bookbuf.length);
  return bookptr;
};
function getDWORDSize(ptr) {
  size = 0;
  for (i = 3; i > -1; i--) {
    size = (size << 8) + Module.HEAPU8[ptr + i];
  }
  return size;
};
function getWORDSize(ptr) {
  size = 0;
  for (i = 1; i > -1; i--) {
    size = (size << 8) + Module.HEAPU8[ptr + i];
  }
  return size;
};
function extractFromHeapBytes(size, ptr) {
  return Module.HEAPU8.slice(ptr, ptr + size);
}
async function getFont(url) {
  r = await fetch(url);
  byteArray = await r.arrayBuffer();
  return byteArray;
}
function _arrayBufferToBase64(buffer) {
  var binary = '';
  var bytes = new Uint8Array(buffer);
  var len = bytes.byteLength;
  for (var i = 0; i < len; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return window.btoa(binary);
}

class audioBook {
  constructor(bookbuf) {
    debugger;
    this.bookbuf = bookbuf;
    let bookheapPtr = copyBufferToHeap(bookbuf);
    this.bookPtr = msdreader.getBookFromBuf(bookheapPtr, bookbuf.length);
    freeHeap(bookheapPtr);  // free heap from bin buffer;
    this.bookPlayerPtr = msdreader.getBookPlayer(this.bookPtr);
    this.firstAtom = msdreader.getFirstAtom(this.bookPtr);
    this.lastAtom = msdreader.getLastAtom(this.bookPtr);
  }
  getDuration() {
    if (this.bookDuration) return this.bookDuration;
    this.bookDuration = msdreader.getVoiceDuration(
        this.bookPlayerPtr, this.firstAtom, this.lastAtom);
    return this.bookDuration;
  }
};
class book {
  // fontHeapPtr = null;
  // fontSize = 42;
  // rendererFormatPtr = null;
  // bookPtr = null;
  // screenWidth = 300;
  // screenHeight = 300;
  // lastBookPosIdicator = null;
  // currentBookPosIndicator = null;
  // bookRendererPtr = null;
  // renderedPagePtr = null;
  /**
   *
   * @param {base64 string of book} bookbin
   * @param {* Uint8Array of font } font
   * @param {* integer of font size} fontSize
   * @param {* text Fore Color} textFColor
   * @param {* Background color} textBColor
   */
  constructor(
      bookbuf, screenWidth, screenHeight, font, fontSize, textFColor,
      textBColor) {
    debugger;
    this.screenHeight = screenHeight;
    this.screenWidth = screenWidth;
    this.fontSize = fontSize;
    this.fontHeapPtr = copyBufferToHeap(font);
    this.rendererFormatPtr = msdreader.getRendererFormat(
        textFColor, textBColor, textFColor, textBColor, this.fontSize,
        this.fontHeapPtr, font.length);
    debugger;
    let bookheapPtr = copyBufferToHeap(bookbuf);
    this.bookPtr = msdreader.getBookFromBuf(bookheapPtr, bookbuf.length);
    freeHeap(bookheapPtr);  // free heap from bin buffer;

    this.bookRendererPtr = msdreader.getBookRenderer(
        this.bookPtr, this.rendererFormatPtr, screenWidth, screenHeight);
    let bookIndicatorPtr = msdreader.initBookIndicator();
    this.currentBookPosIndicator =
        msdreader.BookNextPart(this.bookPtr, bookIndicatorPtr);
    msdreader.deleteBookPosIndicator(bookIndicatorPtr);
  }
  RenderSpecPage(pos) {
    let indic = msdreader.gotoBookPosIndicator(pos.group, pos.atom);
    if (msdreader.is_last_atom(this.bookPtr, indic)) throw new Error('EOF');

    let NextPage = msdreader.renderNextPage(this.bookRendererPtr, indic);
    msdreader.deleteBookPosIndicator(indic);
    if (this.renderedPagePtr) {
      msdreader.deleteRenderedPage(this.renderedPagePtr);
    }
    this.lastBookPosIdicator = this.currentBookPosIndicator;
    this.currentBookPosIndicator =
        msdreader.getBookIndicatorPartOfPageResult(NextPage);
    let img = msdreader.getImageofPageResult(NextPage);
    let imageSize = getDWORDSize(img);
    let pngData = extractFromHeapBytes(imageSize - 4, img + 4);
    let pic = 'data:image/png;base64,' + _arrayBufferToBase64(pngData);
    msdreader.deleteBytePoniter(img);
    this.renderedPagePtr = NextPage;
    return pic;
  };

  renderPrevPage() {
    debugger;
    if (msdreader.is_first_atom(this.bookPtr, this.currentBookPosIndicator))
      throw new Error('EOF');

    let PrevPage = msdreader.renderBackPage(
        this.bookRendererPtr, this.currentBookPosIndicator);
    if (this.renderedPagePtr) {
      msdreader.deleteRenderedPage(this.renderedPagePtr);
    }
    this.lastBookPosIdicator = this.currentBookPosIndicator;
    this.currentBookPosIndicator =
        msdreader.getBookIndicatorPartOfPageResult(PrevPage);
    let img = msdreader.getImageofPageResult(PrevPage);
    let imageSize = getDWORDSize(img);
    let pngData = extractFromHeapBytes(imageSize - 4, img + 4);
    let pic = 'data:image/png;base64,' + _arrayBufferToBase64(pngData);
    msdreader.deleteBytePoniter(img);
    this.renderedPagePtr = PrevPage;
    return pic;
  }
  renderNPages(fromInd, n) {
    let indic = msdreader.gotoBookPosIndicator(fromInd.group, fromInd.atom);
    if (msdreader.is_last_atom(this.bookPtr, indic)) {
      msdreader.deleteBookPosIndicator(indic);
      throw new Error('EOF');
    }

    let pagesPtr = msdreader.renderNextPages(this.bookRendererPtr, indic, n);
    msdreader.deleteBookPosIndicator(indic);
    if (pagesPtr == null) {
      throw new Error('BAD POINTER');
    }
    let len = getDWORDSize(pagesPtr);
    let pageCount = (len - 4) / 4;
    let images = [];
    for (let i = 0; i < pageCount; i++) {
      let imgPtr = getDWORDSize(pagesPtr + 4 + i * 4);
      let imageSize = getDWORDSize(imgPtr);
      let pngData = extractFromHeapBytes(imageSize - 4, imgPtr + 4);
      let pic = 'data:image/png;base64,' + _arrayBufferToBase64(pngData);
      images.push(pic);
      msdreader.deleteBytePoniter(imgPtr);
    }
    msdreader.deleteBytePoniter(pagesPtr);
    return images;
  }
  renderNextPage() {
    debugger;
    if (msdreader.is_last_atom(this.bookPtr, this.currentBookPosIndicator))
      throw new Error('EOF');

    let NextPage = msdreader.renderNextPage(
        this.bookRendererPtr, this.currentBookPosIndicator);
    if (this.renderedPagePtr) {
      msdreader.deleteRenderedPage(this.renderedPagePtr);
    }
    this.lastBookPosIdicator = this.currentBookPosIndicator;
    this.currentBookPosIndicator =
        msdreader.getBookIndicatorPartOfPageResult(NextPage);
    let img = msdreader.getImageofPageResult(NextPage);
    let imageSize = getDWORDSize(img);
    let pngData = extractFromHeapBytes(imageSize - 4, img + 4);
    let pic = 'data:image/png;base64,' + _arrayBufferToBase64(pngData);
    msdreader.deleteBytePoniter(img);
    this.renderedPagePtr = NextPage;
    return pic;
  }
  bookType() {
    return getBookType(this.bookPtr);
  }
  areWeAtEnd() {
    return msdreader.is_last_atom(this.bookPtr, this.currentBookPosIndicator);
  }
  getProgress() {
    let atomC = msdreader.getBookTotalAtoms(this.bookPtr);
    let p =
        msdreader.getBookProgress(this.bookPtr, this.currentBookPosIndicator);
    return p / atomC;
  }
  getCurrentBookIndicator() {
    debugger;
    let g = msdreader.getIndicatorPart(this.currentBookPosIndicator, 0);
    let a = msdreader.getIndicatorPart(this.currentBookPosIndicator, 1);
    return {group: g, atom: a};
  }
  gotoPos(indicator) {
    // has memory leakage
    // be careful of using it
    if (this.renderedPagePtr) {
      // to free current BookPos
      msdreader.deleteRenderedPage(this.renderedPagePtr);
    }
    this.currentBookPosIndicator = msdreader.gotoBookPosIndicator(
        indicator.group || 0, indicator.atom || 0)
  }
  getListOfPageIndicators() {
    let res = msdreader.getBookPosIndicators(this.bookRendererPtr);
    let len = getDWORDSize(res);
    let c = Math.floor((len - 4) / 8);
    let pages = [];
    for (let i = 0; i < c; i++) {
      let g = getDWORDSize(res + 4 + i * 8);
      let a = getDWORDSize(res + 4 + i * 8 + 4);
      pages.push({group: g, atom: a})
    }
    msdreader.deleteBytePoniter(res);
    return pages;
  }

  contentAt(itemIndex) {
    let r = msdreader.getBookContentAt(this.bookPtr, itemIndex);
    if (r == 0) throw new Error('bad Index');
    let size = getDWORDSize(r);
    let gindex = getDWORDSize(r + 4);
    let aindex = getDWORDSize(r + 4 + 4);
    let parentindex = getWORDSize(r + 4 + 4 + 4);
    let sbuf = extractFromHeapBytes(size - 4 - 4 - 4 - 2, r + 4 + 4 + 4 + 2);
    let s = new TextDecoder('utf-8').decode(sbuf);
    return {
      pos: {group: gindex, atom: aindex}, text: s, parentIndex: parentindex
    }
  }
  contentLength() {
    return msdreader.getBookContentLength(this.bookPtr);
  }
}

async function main() {
  let bookbuf = await getFont('book1.msd');
  debugger;
  bookbuf = new Uint8Array(bookbuf);
  let ab = new audioBook(bookbuf);
  console.log(ab.getDuration());
}
async function main1() {
  book64_1 =
      'AABrAQAAxmlzUf9K7CnNuqvy++NGfMJU+Bvo5412Wi5jM5/JmmYyDbcxWKNaJV0FF1jpXtSrss3Gm7RUEQ6CdEEhPdyHcOk+oUHh/Gc+AX6X6txrlo84XCrssDv7Mq88VOwY21wCGv5D+/qqOvsp0eYFPHyUddi+YYn5XLuomQ+VsevxswXv9wDpoTrlygvL0EhHZL0fIx6oHHtkxRRzWsVeS3ljO3BkJBGeCdyq1KzyGxCvOzPN41BIRxVcu28iGbqbffUL4RocfyP4KfikGxO1yk7omDI44HlNPTS8X053+stsBayGISuqGlWivnC1czsEXNM2lLOv4vDknk8yFUn9gk6pCHDUsoopVEiaCrzVDhioRKxb845M1y2bCULlBsQzr82jhH8trdR2R94yHOxKxDD2ICOFbPuyBwT07Au5ILqGwz4F8ezZZzO3mVCj4xTT2TT3XqDyEKj2BZQBvrS8RHj6SWnmI9Aa2mmCaXNR7krsKc2JrfK/5UZbxFS9HejvjXZaLkMzn8GaZjIN/zdYuVolXQU5Xulx0quVy8a2slQ2CII1RyEF2od16T6hJdxpc1H6SuwpzKur8vvhRnzDVPob6eeOdl4u';

  book64_2 =
      'AAAEAAAAfxYAAB0AAAAAJwYASAYAMQYANAYATgYARAYAzAYARQYACAAAAAAgAAAIAAAAACgAAAsAAAAAKAYARwYAEQAAAAA5BgAoBgAxBgDMBgAIAAAAADoAABoAAAAA2QUA6AUA1QUA6QUA3AUA2QUA3QUACwAAAAAoBgAnBgARAAAAACoGAEQGAEEGADgGACAAAAAAzAYAMQYASAYANAYATgYARAYAJwYAzAYARQYAGgAAAAAvBgAxBgAoBgAnBgAxBgBHBgBUBgAOAAAAACcGAMwGAEYGABcAAAAAfgYAMQYASAYARgYALwYARwYAKQAAAABZAABlAAByAAB1AABzAABoAABhAABsAADhAAB5AABpAABtAAAIAAAAAAwGABEAAAAAOQYAMQYAKAYAzAYAGgAAAAAjBgBIBgAxBgA0BgBEBgDMBgBFBgAaAAAAACcGAEQGAEIGAE8GAC8GADMGAA4gABoAAAAAJwYARgYArwYARAYAzAYAMwYAzAYAIAAAAABKAABlAAByAAB1AABzAABhAABsAABlAABtAAAIAAAAACkAAAsAAAAAzAYAJwYAEQAAAABCBgBPBgAvBgAzBgAXAAAAACcGAEQGAEIGAE8GAC8GADMGADIAAAAAKAYATgYAzAYAUgYAKgYADCAAJwYARAYARQYATwYAQgYALwYATgYAUQYAMwYAEQAAAAA0BgBHBgAxBgDMBgALAAAAAC8GADEGABQAAAAALwYAJwYARQYARgYARwYAEQAAAAAsBgAoBgAnBgBEBgAXAAAAACcGAEQGAC4GAEQGAMwGAEQGAAgAAAAASAYADgAAAADMBgCpBgDMBgALAAAAACcGADIGACMAAAAAQgYALwYAzAYARQYAzAYADCAAKgYAMQYAzAYARgYAFwAAAAA0BgBHBgAxBgBHBgAnBgDMBgARAAAAACwGAEcGACcGAEYGAA4AAAAAJwYAMwYAKgYACAAAAAAuAAAjAAAAAEEGAEQGADMGADcGAMwGAEYGAMwGAAwgAEcGACcGACYAAAAAJwYAMwYAMQYAJwYAJgYAzAYARAYAzAYADCAARwYAJwYACwAAAABHBgAxBgALAAAAAC8GAEgGAA4AAAAANAYARwYAMQYACwAAAAAxBgAnBgAXAAAAAH4GACcGAMwGACoGAC4GACoGAA4AAAAALgYASAYALwYAHQAAAABFBgDMBgAMIAAvBgAnBgBGBgBGBgAvBgAaAAAAADcGAEgGADEGAMwGAAwgAKkGAEcGABoAAAAAJwYAMwYAMQYAJwYAJgYAzAYARAYAFwAAAABFBgBIBgAzBgAzBgAnBgAqBgAUAAAAAC8GAEgGAEQGACoGAMwGABEAAAAAJwYANQYARAYAzAYADgAAAABGBgCvBgBHBgAgAAAAAC8GACcGADQGACoGAEcGAAwgACcGADMGACoGABQAAAAALQYAqQYASAYARQYAKgYAHQAAAAAuBgBIBgAvBgCvBgAxBgAvBgAnBgBGBgAXAAAAAEEGAEQGADMGADcGAMwGAEYGAAsAAAAAIgYARgYAFAAAAABGBgBHBgAnBgDMBgAqBgAUAAAAADkGAEYGAEgGACcGAEYGAA4AAAAARQYAQgYAMQYAHQAAAABFBgDMBgAMIAA0BgBGBgAnBgAzBgAvBgAOAAAAACcGAEUGACcGAA4AAAAAKAYALgYANAYAEQAAAAA0BgAxBgBCBgDMBgARAAAAAEYGAEEGAEgGADAGABEAAAAAqQYAMQYALwYARwYADgAAAABGBgA4BgAxBgAUAAAAACwGACcGAEUGADkGAEcGABQAAAAALAYARwYAJwYARgYAzAYAEQAAAAA1BgBIBgAxBgAqBgAgAAAAADoGAMwGADEGAEIGACcGAEYGAEgGAEYGAMwGABQAAAAAJwYAQgYALwYAJwYARQYAIAAAAAA0BgBHBgAxBgCpBgAMIAAzBgAnBgAyBgDMBgAdAAAAAKkGADEGAC8GAEcGAAwgACcGADMGACoGAAsAAAAAMwYARwYADgAAAAAvBgDMBgBGBgARAAAAACgGADIGADEGAK8GAB0AAAAAJwYAKAYAMQYAJwYARwYAzAYARQYAzAYAFwAAAADMBgBHBgBIBgAvBgDMBgAqBgAXAAAAAEUGADMGAMwGAC0GAMwGACoGABQAAAAAJwYAMwYARAYAJwYARQYAEQAAAABFBgBCBgAvBgAzBgAUAAAAACwGAEUGADkGAMwGACoGABoAAAAAJwYASAYAMQYANAYARAYAzAYARQYAFwAAAAD4BgDwBgDwBgDwBgDwBgDwBgAOAAAAAEYGAEEGADEGAA4AAAAAMwYAJwYARAYAEQAAAADyBgDwBgDxBgDyBgAIAAAAAFsAAAgAAAAA8gYACAAAAABdAAAUAAAAAEUGADMGACcGAC0GACoGABQAAAAA8QYA8gYA9QYAawYA8QYAJgAAAACpBgDMBgBEBgBIBgBFBgAqBgAxBgBFBgAxBgAoBgA5BgAFAAAAZBEAAAAAhgYARwYAJwYAMQYAGgAAAADMBgBHBgBIBgAvBgDMBgAnBgBGBgAUAAAAAEUGAC0GADMGAEgGACgGABcAAAAARQYAzAYADCAANAYASAYALwYAEQAAAACpBgBGBgAnBgAxBgARAAAAADUGAEEGACcGAC8GABQAAAAALQYAKAYAMQYASAYARgYAFAAAAAA3BgAoBgAxBgDMBgBHBgAOAAAAAEUGAC0GAEQGABQAAAAAMwYAqQYASAYARgYAKgYAFwAAAAAoBgAzBgDMBgAnBgAxBgDMBgAgAAAAAC8GACcGAEYGADQGAEUGAEYGAC8GACcGAEYGABQAAAAARQYAMAYARwYAKAYAzAYAFAAAAADMBgBHBgBIBgAvBgDMBgAdAAAAACgGAEgGAC8GAEcGAAwgACcGADMGACoGAAgAAAAA8wYAIAAAAABFBgBCBgAvBgAzBgAMIAAqBgAxBgDMBgBGBgAOAAAAAEYGAMwGADIGAAsAAAAAfgYAMwYADgAAAABFBgCpBgBHBgAUAAAAAEUGAC8GAMwGAEYGAEcGABQAAAAAMwYASAYARQYAzAYARgYAEQAAAAAoBgAxBgAnBgDMBgAdAAAAAEUGADMGAEQGAEUGACcGAEYGACcGAEYGABoAAAAARQYALQYAKgYASAYAzAYAJwYAKgYAFAAAAADxBgAJAABGBgAnBgBFBgAgAAAAAPIGAAkAACoGACcGADEGAMwGAC4GAIYGAEcGACkAAAAA8QYACQAAMQYAzAYANAYARwYADCAANAYARgYAJwYAMwYAzAYAFwAAAADzBgAJAABFBgAxBgAvBgBFBgAXAAAAAPEGAAkAADIGACgGACcGAEYGABoAAAAA8gYACQAAQgYASAYARQYAzAYAKgYAFwAAAADzBgAJAABFBgAwBgBHBgAoBgAaAAAAAPQGAAkAAEEGADEGAEcGAEYGAK8GABoAAAAA9QYACQAALAYARQYAOQYAzAYAKgYAFAAAAAD0BgAJAAA0BgBHBgAxBgAUAAAAAEIGAC8GAMwGAEUGAMwGAAgAAAAA9AYAFwAAAADxBgAJAABFBgAtBgBEBgBHBgAdAAAAACcGADEGAEUGAEYGAMwGAAwgAEcGACcGABcAAAAA8gYACQAARQYALQYARAYARwYAHQAAAABFBgAzBgDMBgAtBgDMBgAMIABHBgAnBgAXAAAAAPMGAAkAAEUGAC0GAEQGAEcGACAAAAAARQYAMwYARAYARQYAJwYARgYADCAARwYAJwYAFwAAAAD0BgAJAABFBgAtBgBEBgBHBgAdAAAAAMwGAEcGAEgGAC8GAMwGAAwgAEcGACcGACAAAAAA9QYACQAALAYAOgYAMQYAJwYAQQYAzAYAJwYACAAAAAD1BgAXAAAAAPEGAAkAAC0GADUGACcGADEGABoAAAAA9gYACQAASAYANgYAOQYAzAYAKgYAFAAAAAAtBgBCBgBIBgBCBgDMBgAIAAAAAPYGABQAAAAA8QYACQAAKgYARgYANAYACAAAAADxBgARAAAAAPEGAAkAACgGAEcGABQAAAAAMQYAMwYARQYAzAYAKgYAFwAAAAA0BgBGBgAnBgAuBgAqBgBGBgAaAAAAAEYGADQGAEYGACcGAC4GACoGAEYGABcAAAAARQYAMQYAMgYARwYAJwYAzAYAEQAAAADxBgD5BgD2BgD3BgAaAAAAAPIGAAkAACcGADQGADoGACcGAEQGABoAAAAAQQYARAYAMwYANwYAzAYARgYAzAYAEQAAAAAqBgBIBgAzBgA3BgAaAAAAAPMGAAkAACoGADEGACcGAEUGAH4GABEAAAAAKgYANgYAJwYALwYAFwAAAAAzBgAnBgAyBgBFBgAnBgBGBgAOAAAAAEUGAEQGAEQGABoAAAAA9wYACQAARQYAMQYAJwYAqQYAMgYAFwAAAAAiBgBFBgBIBgAyBgA0BgDMBgAgAAAAAPgGAAkAACcGAEgGADEGADQGAEQGAMwGAEUGABEAAAAAIgYAKwYAJwYAMQYAIwAAAAD5BgAJAAAsBgAzBgAqBgAnBgAxBgBHBgAnBgDMBgAXAAAAAEgGACcGACgGADMGACoGAEcGACAAAAAA8QYA8AYACQAAfgYAJwYARgYASAYAzAYAMwYAHQAAAADxBgDxBgAJAABFBgBGBgAnBgAoBgA5BgAOAAAAAEYGACcGAEUGABcAAAAARgYASAYANAYAKgYAJwYAMQYAGgAAAABGBgAnBgBFBgAMIABHBgAnBgDMBgARAAAAAC8GAMwGAK8GADEGABEAAAAAMgYAKAYAJwYARgYAIAAAAADMBgAxBgBIBgA0BgBEBgAnBgDMBgDMBgBFBgAOAAAAAEIGAC8GADMGABoAAAAARQYAzAYADCAAKgYASAYAJwYARgYAFwAAAAAsBgAxBgBIBgAzBgBEBgBFBgAjAAAAACgGAMwGACoGAAwgACcGAEQGAEUGAEIGAC8GADMGABQAAAAAJwYANAYAJwYAMQYARwYADgAAAACpBgAxBgAvBgAaAAAAAEUGACoGAEYGAAwgAEcGACcGAMwGABQAAAAAfgYARwYARAYASAYAzAYAGgAAAABVAAByAABpAABhAQBsAAArAQBtAAAOAAAAAMwGACcGAC8GABoAAAAANAYALwYARwYADCAAJwYAMwYAKgYAFAAAAABFBgBGBgAnBgAoBgA5BgAUAAAAAEEGACcGADEGADMGAMwGABcAAAAAKAYARwYADCAANwYASAYAMQYAEQAAAAA5BgBFBgAvBgBHBgAUAAAAACcGAMwGAEQGAMwGACcGABcAAAAAJwYASAYAMQYANAYARAYARQYAEQAAAAAoBgAxBgAuBgDMBgAaAAAAACcGAMwGAEQGAMwGACcGADMGACoGAAsAAAAAqQYARwYAFwAAAAAvBgAnBgBGBgAzBgAqBgBHBgARAAAAAK8GAEEGACoGAEcGAB0AAAAARgYAJwYARQYAzAYADCAAJwYAMwYAKgYAGgAAAAB+BgAnBgAxBgAzBgDMBgAnBgBGBgAgAAAAACgGACcGADIGAC4GAEgGACcGAEYGAEYGAC8GAAgAAAAA9wYAGgAAAAA0BgBHBgAxBgAzBgAqBgAnBgBGBgARAAAAADIGAEUGAMwGAEYGAAgAAAAA+AYAEQAAAAAoBgBEBgBCBgAnBgAaAAAAACcGADEGAMwGAC0GACcGADMGACoGAC8AAAAAKAYAzAYAKgYADCAAJwYARAYARQYATwYAQgYATgYALwYATgYAUQYAMwYALAAAAAAoBgDMBgAqBgAMIAAnBgBEBgBFBgBOBgBCBgBSBgAvBgBOBgAzBgAOAAAAAKkGACcGADEGAB0AAAAAMQYAQQYAKgYARwYADCAAJwYAMwYAKgYAEQAAAACvBgAxBgCGBgBHBgAaAAAAACcGADUGAMwGAEQGAAwgACoGADEGAAsAAAAAFCAASAYAFAAAAAAqBgAxBgCpBgDMBgAoBgAOAAAAANEFANkFAOoFABQAAAAA1AUA3gUA5wUA0wUA6QUADgAAAAAoBgDMBgAqBgAUAAAAAEcGAEUGAEIGAC8GADQGAB0AAAAALgYASAYAzAYANAYAJwYASAYARgYALwYACAAAAAAUIAApAAAAACgGAMwGACoGAAwgACcGAEQGAEUGAEIGAC8GAE4GAFEGADMGAA4AAAAALgYAJwYANQYAHQAAAACvBgBGBgAsBgAnBgBGBgDMBgAvBgBGBgAOAAAAACgGAC0GADEGABcAAAAARQYAKgYAQgYAJwYAMQYAKAYAFAAAAAAoBgA5BgA2BgAnBgBLBgAOAAAAAEcGADIGACwGABQAAAAARQYARgYAJwYAMwYAKAYADgAAAAA0BgA5BgAxBgAUAAAAAK8GADEGAEEGACoGAEcGAAgAAAAA+QYAEQAAAABFBgAqBgBIBgBGBgAOAAAAAKkGAEcGAEYGAA4AAAAARgYAOAYARQYADgAAAABGBgArBgAxBgAOAAAAACgGAEYGACcGABQAAAAArwYAQQYAKgYARwYAVAYAFwAAAABBBgAxBgAvBgBIBgAzBgDMBgAUAAAAAK8GAE4GAEYGAK8GAFIGAA4AAAAALwYAUAYAmAYAFAAAAABHBgBIBgAuBgBSBgAqBgARAAAAAC4GADQGAKkGAMwGABcAAAAAMQYAMwYAzAYALwYARgYALwYACwAAAAAzBgAxBgARAAAAAKkGAMwGAEYGAEcGABoAAAAALAYASAYAzAYACQAACQAAKAYARwYAGgAAAABGBgBQBgBHBgAnBgAvBgBGBgAvBgAOAAAAADEGAEgGAMwGAAsAAAAAKAYAMQYAHQAAAAB+BgBHBgBEBgBOBgBIBgAnBgBGBgDMBgAmAAAAADEGACcGAEYGAC8GAEYGAC8GAAkAAAkAAEcGAEUGAMwGAAgAAAAAqwAAHQAAAACvBgBOBgBGBgCvBgAMIAAvBgBQBgCYBgAIAAAAALsAAAsAAAAATgYANAYAGgAAAAAuBgBIBgAnBgBGBgAvBgBGBgAvBgAaAAAAACgGAEcGAAwgACoGACcGADIGAMwGABEAAAAAqQYARgYASAYARgYAFAAAAAAuBgAnBgBGBgBHBgBUBgAOAAAAAH4GACcGAKkGACwAAAAALgYASAYAJwYARgYACQAACQAAKAYAMQYAIgYASAYAMQYALwYARwYAFAAAAAAnBgDMBgBIBgAnBgBGBgAUAAAAADYGAC0GAFEGACcGAKkGAA4AAAAALwYAJwYARgYACwAAAADxBgDwBgAUAAAAADMGAMwGACcGADMGACoGABEAAAAAMQYAMwYARQYAzAYAEQAAAAAvBgBIBgBEBgAqBgAUAAAAACcGAEQGADIGACcGAEUGABoAAAAARQYAzAYADCAALwYAJwYAMQYALwYAKQAAAAAjBgBPBgBIBgAxBgBPBgA0BgBOBgBEBgBQBgDMBgBFBgBOBgALAAAAAEcGAEUGABEAAAAAMQYAzAYANAYARwYACwAAAAAzBgAqBgA+AAAAACMGAE8GAEgGADEGAE8GADQGAE4GAEQGAFAGAMwGAEUGAE4GAC0AACcGAEQGAEIGAE8GAC8GADMGABEAAAAAKAYAMQYASAYALwYACwAAAADxBgDxBgCcCAAABQAAAAFVAAAAAgAAAQACAAMAAQAEAAUAAQAGAAEABwABAAgAAQAJAAEACgABAAsAAQAMAAEADQAOAAEAAwABAA8ABQABABAAAQARAA4AAQADAAEAEgAFAAEACwAAAAETABQAAQAzCAAAAhUAAQAWAAEAAgADAAEADwAFAAEAFwAUAAEAFQABABgADgABABkAAQAaAAEAGwABABwAAQAdAAEAHgABAB8AAQAgAAEAIQABACIAAQAjAAEAJAAlAAEAJgABAB4AAQAnAAEAKAABACkAAQALAAEAKgABACsAAQAsAAEALQABAC4ADgABAC8AAQAwAAEAMQABADIAAQAzAAEALQABACsAAQAaAAEACwABACoAAQA0AAEANQABAB4AAQA2AAEANwABADgAAQA5AAEAKwABABoAAQA6AAEAAwABADsAAQA8AAEANgABAC0AAQA9AAEAPgABADAAAQAaAAEAPwABAEAAAQA5AAEAQQABAEIAAQAeAAEAHgABACAAAQBDAAEARAABAEUAAQADAAEARgABAEcAAQBIAAEAAwABAEkAAQBKACUAAQALAAEAKgABACAAAQBDAAEAKAABAEsAAQBMAAEATQABAE4AAQBPAA4AAQBQAAEAHgABAFEADgABAFIAAQAkACUAAQBTAAEAVAABAFUAAQBWAAEAAgBXAAEAWAAUAFkAWgBbAAEAHgABAFwAAQA5AAEAXQABAF4AAQAkACUAXwBfAFQAAQAfAAEAIAABAGAAAQAqAAEAUgABAGEAAQBiAAEAYwABAB4AAQAaAAEAZAABACIAAQBlAA4AAQBmAAEAHgABAGcADgABAGgAAQBpAAEAagABACAAAQBrAAEAbAABAG0AAQBuACUAWQBvAFsAAQALAAEAKgABAHAAAQAqAAEAGgABAFAAAQBiAAEAYwABAB4AAQBxAAEAcgABACAAAQBzAAEAHgABAHQADgABAHUAAQAqAAEAUgABAHYAAQB3AAEAJAAlAF8AXwB4AF8AeQBfAHoAXwBaACUAewABAFQAXwB8AF8AbwAlAH0AXwBvACUAfgBfAG8AJQB/AF8AbwAlAIAAXwBvACUAgQBfAIIAAQCDAAEAVABfAIQAJQCFAAEAhgBfAIQAJQCHAAEAiABfAIQAJQCJAAEAigBfAIQAJQCLAAEAjABfAI0AXwCOACUAjwABAFQAXwCQAAEAkQBfAJIAJQCTAAEALAABADAAAQAeAAEAVABfAJIAJQCUACUAlQABAJYAAQCXAAEAFQABAJgAAQCZAAEAmgABADAAXwCSACUAlAAlAJsAAQA/AAEAnAABAJ0AAQAwAF8AkgAlAJQAJQCeAAEAHgABADAAAQAaAAEAnwABAAcAAQCgAAEAoQBfAKIAAQCjAF8ApAABABoAAQClAF8ApgABAKcAXwCoAF8AqQBfAKoAXwCrAAEAMwAFAAEArAABAK0AAQBUAF8AqgABAAsAAQAqAAEAGgABAK4AAQAEAAEArwABAB4AAQAaAAEArgABAA8AAQCwAAEAJAAlAAEAIAABAK0AAQCsAAEACwABACoAAQCxAAEAAwABALIADgABAFQAAQAVAAEAswABALQAAQC1ACUAWQBaAFsAXwBfABoAAQC2AAEAtwABACAAAQALAAEAKgABAAcAAQCqAAEAVAABAAIAuAAUAAEAuQABALoAJQBZAIQAWwABAHIAAQAgAAEAUQABABoAAQC7AAEAvAABACAAAQALAAEAKgABAL0AAQC+AAEABwABAEsAAQCqAAEAvwAOAAEAVAABAAIAFQABAMAAFAABAB4AAQCzAAEAuQABALoAJQBZAI4AWwABABoAAQDBAAEAIAABALsAAQC8AAEACwABAMIAAQDDAAEAqgABAAQAAQAqAAEAxAABALoAWQCSAFsAAQAeAAEAcQABAMUAAQC6AAEAwwABAFQAAQDGAAEAwwABAMEAAQDHAAEAKgABACsAAQADAAEAOQABAMgAJQBZAMkAWwABABoAAQDBAAEAuwABAL8AAQAfAAEAIAABAEsAAQDKAAEAywABALMAAQDEAAEAugAlAFkAzABbAAEAKQABAMoAAQCtAAEAKwABAKoAAQDNAAEAHgABAM4AJQBZAMwAWwABACgAAQApAAEARgABAM8AAQAeAAEA0AABABoAAQCuAAEAvAABAAMAAQDRAAEA0gAlAAEA0wABAEYAAQDQAAEA1AABACQAAQDVAAEA1gABAAQAAQDXAAEA2AABAAIA2QABANoAFAABAAcAAQA5AAEA2wABACQAAQDcAAEARgABAN0AAQC9AAEA3gABAHYAAQDfAAEAGgABAOAAAQDhAAEAAgAeAAEA4gABAOMAFAABAOQAAQAkAAEAHgABABoAAQDlAAEAvAABAAMAAQDRAAEA5gABALoAJQBZAOcAWwBfAF8AGgABAGoAAQAgAAEA6AABAOkAAQDqAAEAHgABAOsAAQC8AAEAIAABAAsAAQAqAAEABwABAKoAAQCzAAEAuQABALoAAQAeAAEA7AABAAMAAQDtAAEA7gABAKoAAQALAAEAKgABABoAAQCuAAEAtwAOAAEA7wABAPAAAQDxAAEAbgAFAF8AXwADAAEA8gABAPMAAQD0AAEA9QABAPYAAQCzAAEA9wABAPgAXwDDAAEA+QABAPoAAQCuAAEA+wABAPwA/QABAPEA/gABAP8AAQAAAV8AAQEBAAIBAQD8AAMBAQAEAf4AAQAFAQEABgEBAAcBAQAIAV8AWQAJAVsAXwBfAAoBAQALAQEADAEBADAADgABAA0BAQAOAQEAwwABAA8BDgABAMMAAQAQAQEAEQEBAKwAAQAEAAEAHgABABIAAQASAQ4AAQAaAAEAZAABABcAAQADAAEARgABABMBAQADAAEA0QABABQBJQBZABUBWwBfAA=='
  book64_3 =
      'AAAEAAAALRIAABEAAAAALwYAqQYAKgYAMQYACAAAAAAgAAARAAAAADMGADEGAEYGACcGAA4AAAAAIgYARgYARgYAFAAAAACGBgBGBgAzBgBEBgAxBgAIAAAAAAwGABEAAAAALAYAMQYAJwYALQYAFAAAAAB+BgAxBgBIBgAnBgAyBgALAAAAAPQGAPMGABQAAAAAMwYAJwYARAYARwYADCAACwAAAAAoBgBHBgAOAAAAAEUGAC8GACoGAAsAAAAA8QYA8wYADgAAAAAzBgAnBgBEBgARAAAAAEYGACcGADMGACcGABEAAAAALgYALwYARQYAKgYAFAAAAACpBgAxBgAvBgBHBgAMIAARAAAAACcGADMGACoGABsGABQAAAAAOQYARAYAJwYASAYARwYACwAAAAAoBgAxBgAOAAAAACcGAMwGAEYGAAsAAAAAJwYASAYACwAAAAAvBgAxBgAgAAAAADIGAEUGAMwGAEYGAEcGAAwgAEcGACcGAMwGABcAAAAARQYARwYARgYALwYAMwYAzAYADgAAAAAoBgAxBgBCBgAUAAAAADoGAEgGACcGADUGAMwGAAgAAAAASAYAEQAAAAB+BgAyBgA0BgCpBgAdAAAAAEcGAEgGACcGAEEGADYGACcGAMwGAMwGABQAAAAALwYAJwYALgYARAYAzAYACwAAAABHBgBFBgARAAAAACoGAC4GADUGADUGABEAAAAALwYAJwYAMQYALwYACAAAAAAuAAAUAAAAACcGAC4GAMwGADEGACcGAAsAAAAAfgYAMwYACwAAAAAnBgAyBgAUAAAAACcGAEIGACcGAEUGACoGAAgAAAAA9gYAEQAAAABFBgAnBgBHBgBHBgAOAAAAAEEGADYGACcGABEAAAAAMgYARQYAzAYARgYAGgAAAAAoBgAnBgAyBgCvBgA0BgAqBgBHBgAOAAAAADMGAEEGADEGAB0AAAAArwYAMQYASAYARwYADCAARwYAJwYAzAYAFwAAAAAnBgA5BgAyBgAnBgBFBgDMBgALAAAAAPUGAPYGAAsAAAAA9QYA9wYAEQAAAABCBgAxBgAnBgAxBgAaAAAAAEUGAMwGAAwgAK8GAMwGADEGAC8GAAUAAABkEQAAAACvBgAxBgCGBgBHBgAXAAAAACoGACcGAKkGAEYGAEgGAEYGABEAAAAANQYALwYARwYAJwYADgAAAABGBgBBBgAxBgAdAAAAADEGAEEGACoGAEcGAAwgACcGAEYGAC8GAA4AAAAAJwYARQYAJwYAIAAAAAB+BgCYBgBIBgBHBgA0BgAMIABHBgAnBgDMBgAdAAAAADEGAMwGADIGAK8GADEGACcGAEYGADQGABQAAAAARQYAJwYARgYARgYALwYAGgAAAAAoBgBHBgAMIAA1BgBIBgAxBgAqBgAXAAAAAEUGADMGACoGAEIGAMwGAEUGABoAAAAAMQYASAYANAYADCAARwYAJwYAzAYAFwAAAAAvBgAxBgBFBgAnBgBGBgDMBgAOAAAAADEGAEgGAMwGABQAAAAAKgYAIwYAKwYAzAYAMQYAIAAAAABFBgDMBgAMIACvBgAwBgAnBgAxBgBGBgAvBgALAAAAACgGACcGAA4AAAAARwYALwYAQQYAFwAAAAAnBgBBBgAyBgAnBgDMBgA0BgARAAAAAC8GACcGAEYGADQGAB0AAAAALwYAMQYAKAYAJwYAMQYARwYADCAAzAYADgAAAAAoBgAvBgBGBgAUAAAAACcGAEYGADMGACcGAEYGABcAAAAARwYARQYAhgYARgYAzAYARgYAFAAAAAAoBgBHBgAoBgBIBgAvBgAUAAAAADIGAEYGAC8GAK8GAMwGABQAAAAAJwYAQQYAMQYAJwYALwYAFAAAAABFBgAoBgAqBgBEBgAnBgAUAAAAADMGADEGADcGACcGAEYGACAAAAAAfgYAJwYAMQYAqQYAzAYARgYAMwYASAYARgYAEQAAAAB+BgBIBgCpBgDMBgAaAAAAACcGADMGACoGAC4GAEgGACcGAEYGACMAAAAAIgYAMgYARQYAJwYAzAYANAYADCAARwYAJwYAzAYAFwAAAABFBgAqBgA5BgAvBgAvBgDMBgALAAAAADEGACcGABQAAAAAJwYARgYALAYAJwYARQYAEQAAAAAvBgAnBgAvBgBHBgAOAAAAACcGADMGACoGABoAAAAARQYAzAYADCAArwYASAYAzAYALwYACAAAAAA6AAAUAAAAACcGACgGACoGAC8GACcGAB0AAAAARQYAzAYADCAALwYAJwYARgYAMwYAKgYAEQAAAAAxBgBIBgAyBgDMBgAOAAAAACoGADEGAKkGABQAAAAALgYASAYAJwYARwYALwYADgAAAACpBgAxBgAvBgARAAAAAEgGAEIGACoGAMwGAAsAAAAA8QYA9QYAEQAAAAAzBgAnBgBEBgBHBgAOAAAAACgGAEgGAC8GABEAAAAAKAYAMQYAJwYAzAYAIAAAAAAnBgBIBgBEBgDMBgBGBgAMIAAoBgAnBgAxBgAOAAAAADcGADkGAEUGABEAAAAAhgYANAYAzAYALwYAFwAAAAAiBgCpBgAnBgAvBgBFBgDMBgAUAAAAAEEGADYGACcGAMwGAMwGABEAAAAARQYAMQYAqQYAMgYAEQAAAAAxBgAnBgCpBgAqBgApAAAAACcGAMwGACcGAEQGACcGACoGAAwgAEUGACoGAC0GAC8GAEcGAB0AAAAARwYAJwYARgYAKgYAMwYASAYAzAYARAYAGgAAAAAiBgBEBgAnBgAoBgAnBgBFBgAnBgAOAAAAAEYGAEIGADQGAAsAAAAAzAYAqQYAGgAAAABFBgAjBgBFBgBIBgAxBgDMBgAqBgAgAAAAADQGACgGAMwGAEcGAAwgADMGACcGADIGAMwGABQAAAAAKgYALAYAMQYAKAYARwYAEQAAAACpBgBFBgB+BgDMBgAUAAAAACIGAEUGAEgGADIGADQGAB0AAAAAQQYANgYAJwYARgYASAYAMQYALwYAzAYAFAAAAAAnBgAsBgAxBgAnBgDMBgAgAAAAACcGADkGADIGACcGAEUGAAwgAEcGACcGAMwGACYAAAAALwYAJwYARgYANAYADCAAIgYARQYASAYAMgYAJwYARgYAFwAAAAAoBgBHBgAMIAA0BgAvBgAqBgAOAAAAACoGAC0GACoGABEAAAAArwYAMQYAQQYAKgYADgAAAAB+BgAvBgAxBgAUAAAAAEUGACcGAC8GADEGADQGABEAAAAARQYASAYAMQYALwYACwAAAAAiBgBGBgAaAAAAAH4GADEGADMGAMwGAC8GAEYGAC8GABEAAAAAfgYAJwYAMwYALgYADgAAAAAvBgAnBgAvBgAIAAAAAKsAAA4AAAAAqQYAJwYAMQYAEQAAAABHBgBFBgAnBgBGBgARAAAAAKkGACcGADEGAMwGAAsAAAAAqQYARwYAEQAAAAAvBgBIBgAzBgAqBgARAAAAAC8GACcGADEGAEUGABEAAAAAKgYARQYAJwYARQYADgAAAAA5BgBFBgAxBgAOAAAAAKkGAEYGAEUGAAgAAAAAuwAAFAAAAAAqBgAnBgAxBgDMBgAuBgARAAAAAJgGAEgGACYGAEYGABEAAAAA8gYA8AYA8QYA+AYAGgAAAAAnBgDMBgAzBgAqBgCvBgAnBgBHBgAdAAAAACgGACcGAMwGAKkGACcGAEYGAEgGADEGABQAAAAAMQYASAYAMwYAzAYARwYAHQAAAABCBgAyBgAnBgBCBgAzBgAqBgAnBgBGBgAOAAAAADEGAEEGACoGAB0AAAAARwYARQYAMQYAJwYARwYADCAAKAYAJwYAHQAAAAAnBgBEBgCpBgAzBgAnBgBGBgAvBgAxBgARAAAAAK8GADEGADMGACoGABQAAAAARQYARwYARgYALwYAMwYAFwAAAAAiBgBEBgBFBgAnBgBGBgDMBgARAAAAADMGADEGACwGAMwGAB0AAAAAfgYAMQYASAYAqQYASAYAfgYAzAYAQQYAIAAAAABBBgAxBgBFBgAnBgBGBgAvBgBHBgAMIADMBgARAAAAADEGAEgGADMGAMwGAB0AAAAAQQYANgYAJwYAfgYAzAYARQYAJwYAzAYAFAAAAAAzBgAnBgDMBgBIBgAyBgAUAAAAAE0AAFMAAC0AADAAADkAACAAAAAAfgYAzAYANAYAMQYAJwYARgYARwYADCAAzAYADgAAAAD0BgDyBgDxBgARAAAAAEcGADIGACcGADEGABoAAAAAqQYAzAYARAYASAYArwYAMQYARQYAEQAAAAAzBgAxBgA5BgAqBgARAAAAAPEGAPcGAPcGAPAGABoAAAAAqQYAzAYARAYASAYARQYAKgYAMQYAEQAAAAAzBgAnBgA5BgAqBgAOAAAAAC4GAEgGAC8GABEAAAAAIgYAOgYAJwYAMgYADgAAAADMBgAnBgAvBgAaAAAAAEUGAMwGAAwgACIGAEgGADEGAC8GABEAAAAAMgYARQYAJwYARgYAFAAAAAB+BgAxBgAqBgAnBgAoBgAXAAAAAEUGACoGAEUGADEGAKkGADIGAA4AAAAARwYANAYAKgYAFAAAAAAvBgBCBgDMBgBCBgBHBgAOAAAAAIYGAEcGAEQGABQAAAAAKwYAJwYARgYAzAYARwYAEQAAAABEBgAnBgAyBgBFBgAUAAAAADEGADMGAMwGAC8GAEYGABEAAAAARQYALwYAJwYAMQYAFwAAAAAnBgAxBgAqBgBBBgAnBgA5BgAXAAAAACoGAEIGADEGAMwGACgGAMwGAA4AAAAA8gYA8AYA9wYADgAAAAA5BgDMBgBGBgAOAAAAAC0GACcGAEQGABEAAAAAKAYAJwYAzAYALwYAEQAAAABGBgAoBgBIBgAvBgAOAAAAAC4GADcGACcGABQAAAAARQYANwYARQYAJgYARgYAFAAAAABFBgDMBgAMIAA0BgAvBgAgAAAAACwGADAGACcGACgGAAwgACoGADEGAMwGAEYGAA4AAAAAKAYALgYANAYAFAAAAAAyBgBFBgAnBgBGBgDMBgARAAAAAH4GAEgGADQGADQGABQAAAAAJwYANwYAMQYAJwYAQQYAFAAAAACpBgB+BgAzBgBIBgBEBgARAAAAAKkGAEYGACcGADEGABcAAAAAKgYASAYAJwYARgYAMwYAKgYAFAAAAAAoBgAoBgDMBgBGBgAvBgALAAAAADcGAMwGAAsAAAAA8wYA9AYAFAAAAAAyBgBFBgDMBgBGBgDMBgAOAAAAAEkAAFMAAFMAAA4AAAAASAYANQYARAYACwAAAAA0BgAvBgAdAAAAACgGAEcGAAwgACIGADEGACcGAEUGAMwGABEAAAAALQYAJwYARAYAzAYAHQAAAAAvBgAzBgAqBgAMIABHBgAnBgDMBgA0BgAOAAAAACgGACcGADIGABEAAAAAqQYAMQYALwYARwYAEQAAAAAvBgAnBgAuBgBEBgAUAAAAADQGAEYGACcGAEgGADEGABEAAAAARAYALQYAOAYARwYADgAAAABFBgA6BgAyBgAUAAAAAC8GAEIGAMwGAEIGACcGAB0AAAAARgYARQYAzAYADCAALwYAJwYARgYALwYACwAAAACGBgBHBgAOAAAAAC8GAEcGAC8GABEAAAAAMgYAzAYAMQYAJwYADgAAAABHBgDMBgCGBgAXAAAAAEYGAEIGADcGAEcGAAwgAMwGABEAAAAAKAYAJwYARAYAJwYAFwAAAAB+BgAnBgDMBgDMBgBGBgDMBgARAAAAAEgGACwGAEgGAC8GABQAAAAARgYALwYAJwYAMQYALwYAIAAAAABFBgDMBgAMIAAqBgBIBgAnBgBGBgDMBgAvBgAOAAAAADMGAEIGAEEGABoAAAAALwYAzAYASAYAJwYAMQYARwYAJwYACwAAAADMBgAnBgALAAAAAKkGAEEGABEAAAAALQYAMQYAqQYAKgYAFAAAAACpBgBGBgDMBgAvBgAbBgAXAAAAAEUGAEgGAEIGADkGAMwGACoGABQAAAAArwYAMQYAQQYAKgYARQYAEQAAAAAuBgDMBgBEBgDMBgAOAAAAAK8GAMwGACwGAA4AAAAANAYALwYARQYAFAAAAABGBgAoBgBIBgAvBgBFBgAOAAAAAKkGACwGACcGABEAAAAARwYAMwYAKgYARQYAZAYAAAUAAAAB2wMAAAIAAAEAAgABAAMAAQAEAAUAAQAGAAEABwABAAgAAQAJAAEACgABAAsAAQAMAAEADQABAAoAAQAOAAEADwABABAAAQARAAEAEgABABMAAQAUAAUAAQAVAAEAFgABABcAAQAYAAEAGQAFAAEAGgABABsAAQAcAAEAHQABABsAAQAeAAEAHwABACAAAQAhACIAAQAEAAEAIwABACQAAQAlAAEAJgABACcAAQAoAAEAFgABACkAAQAKAAEAKgABACsAAQARAAEALAABABUAAQAWAAEALQABAC4AAQAvAAEAGwABADAAAQAxAAEAMgAiADMAMwA0AAEANQABADYAAQA3AAEACgABACkAAQA4AAEAOQABADoAAQA7AAEAPAABADoAAQAEAAEAPQABAD4AAQATAAEAPwABAEAAAQBBAAEAKgABAEIAAQBDACIAAQAEAAEARAABAEUAAQBGAAEARwABAEgAAQBJAAEASgABABsAAQBLAAEATAABAE0AAQBOAAEATwABAAoAAQBQAAUAAQBRAAEAGwABAFIAAQBTAAUAAQBUAAEAVQABAFYAAQAWAAEAKQABAFcAAQBYAAEAWQAiAAEAFQABAFoAWwAzABUAAQBaAAEAJQABAFwAAQBdAAEAXgABACoAAQBWAAEAXwABAGAAAQBhACIAAQBiAAEAAwABAAQAAQBjAAEAZAABAGUAAQBmAAEAZwABAGgAAQApAAEAVgABAGkAAQAbAAEAFgABAGoAAQBrAAEAbAABAG0AAQAbAAEAawABAG4AAQAWAAEAbwABAHAAAQAWAAEAcQABAHIAAQAGAAEABwAFAAEAcwABAHQAAQBrAAEAVgABAHUAAQBhACIAAQAUAAEAbAABAHYAAQBmAAEAdwABAHgAAQAbAAEAeQABAHoAAQBrAAEAZgABAHsAAQBZACIAAQAEAAEAfAABAH0AAQBCAAEAFAABAHUAAQAxAAEAfgABABsAAQBiAAEAfwABABsAAQCAAAEAFgABAIEAAQCCAAEAdQABACUAAQAVAAEAgwAFAAEAhAABAIUAWwABAIYAFAABAIcAAQCIAAEAiQABAFkAAQCKAAEAiwABAIwAAQCNAAEAjgABAHUAAQCPACIAkAAzAAMAAQAEAAEAFgABAJEAAQAnAAEAkgABAJMAAQAlAAEAlAABAGsAAQCVAAEAlgABABYAAQCXAAEACgABACkAAQCYACIAAQAEAAEAmQABAJoAAQCbAAUAAQCcAAEABwABAJ0AAQAbAAEAngABAJ8ABQABAKAAAQChAAEARAABAKIAAQCjAAEACQAAAAGkAAEAVwEAAAJEAAEApQABAKYAAQCnAAEAqAABABsAAQCpAAEAqgABAKsAAQATAAEArAABACwAAQCtAAEAVgABAK4AAQBhACIAMwAzADMABAABAAoAAQCvAAEAsAABAIoAAQAlAAEAsQABALIAAQCzAAEAEwABALQAAQC1AAEAGwABALYAAQC3AAEAsQABALgAAQBmAAEAuQABAAoAAQC6AAEAFgABALsAAQC8AAEAvQABAKsAAQBlAAEAGwABABYAAQC+AAEAvwABAMAAAQAlAAEAwQABAMIAAQDDAAEAxAAiAAEAxQABAMYAAQAsAAEAxwABAGUAAQCKAAEAyAABAMkAAQDKAAEAywABAJgAAQAbAAEAFQABAGYAAQBnAAEAzAABACoAAQBWAAEAJQABACkAAQDNACIAAQCjAAEAJAABACUAAQDOAAEAzwABALoAAQDQAAEACgABAAkAAAAB0QABABcBAAAC0gABANMAIgABAAMAAQDUAAEAGwABABYAAQDVAAEAigABANYAAQBWAAEA1wABANgAAQBlAAEA2QABAMoAAQDaAAEA0wAiAAEAFQABAFoAWwAzABYAAQAUAAEA2wABANwAAQDdAAEA3gABAN8AAQCJAAEAVgABAMAAAQBXAAEA4AABAOEAAQDiAAEA4wABAOQAAQAbAAEA5QABAOYAAQDnACIAAQDoAAEAyQABAOkABQABAOoAAQDrAAEA7AABAO0AAQDuAAEAOQABAGIAAQBmAAEAZwABABYAAQAUAAEA7wABADEAAQDwAAUAAQDxAAEA8gABAPMAAQDhAAEA3QABAMMAAQD0AAEA9QABAPYAIgAzAA==';
  book64 =
      'AAAEAAAAYRQAABQAAAAAQgAAbwAAbwAAawAAMQAAGgAAAABDAABoAABhAABwAAB0AABlAAByAAAIAAAAACAAABQAAAAARgAAaQAAcgAAcwAAdAAAEQAAAAAuBgBIBgAvBgA0BgARAAAAAC0GADMGAMwGAEYGAAgAAAAAIQAADgAAAAA0BgBIBgBFBgALAAAAAKkGAEcGABQAAAAALAYARQYARwYASAYAMQYADgAAAAAtBgCpBgBFBgAaAAAAAC4GAEgGADQGAC0GACcGAEQGAEUGAAsAAAAAKAYARwYACwAAAAAnBgAyBgAOAAAAAC0GACoGAMwGAAgAAAAAIgAACwAAAABGBgBHBgAXAAAAAEEGADEGAMwGAC8GAEgGAEYGAAsAAAAARQYAzAYAFAAAAAAoBgAxBgAnBgAvBgAxBgALAAAAAC8GADEGABEAAAAAKgYARgYARwYAJwYAEQAAAAAvBgBIBgAzBgAqBgARAAAAAEUGAEIGACcGAEUGAAgAAAAASAYACwAAAAAiBgBGBgALAAAAADEGACcGABcAAAAAQgYAMQYAKAYAJwYARgYAzAYACwAAAABFBgBGBgAUAAAAAEYGADgGACcGAEUGAMwGAA4AAAAAQgYAKAYARAYADgAAAAAvBgAnBgAvBgARAAAAACcGAEgGAMwGAEYGAA4AAAAALgYASAYALwYAFAAAAAAvBgAnBgA0BgAqBgBHBgAXAAAAACcGAEYGAEIGAEQGACcGACgGABEAAAAAKgYARAYAJwYANAYAFAAAAABFBgA5BgAxBgBBBgDMBgAXAAAAAEQGAC0GADgGACcGACoGAMwGAAsAAAAAzAYAqQYAGgAAAAAnBgDMBgBGBgAsBgAnBgBGBgAoBgARAAAAADEGAMwGAMwGADMGABQAAAAAKgYASAYAJwYARgYALwYAEQAAAACvBgBBBgAqBgA6AAAXAAAAAKsAACcGACwGADEGACcGAMwGAAsAAAAAJwYARQYAEQAAAABGBgAoBgBIBgAvBgAOAAAAACcGAMwGAEYGABEAAAAARgYANAYAJwYARgYAFAAAAABFBgAyBgDMBgAqBgDMBgARAAAAACgGACcGADQGAC8GAA4AAAAARwYAzAYAhgYAEQAAAAAoBgBIBgAvBgBGBgAUAAAAACcGACoGAEcGACcGAEUGABEAAAAAqQYAMQYALwYARwYACAAAAAAuAAARAAAAACgGADEGACcGAMwGAA4AAAAAMgYALwYARwYADgAAAABGBgBBBgAxBgAUAAAAAEYGACgGAEgGAC8GAEcGABQAAAAALwYAMQYAqQYAJwYAMQYADgAAAAAtBgAxBgBBBgAOAAAAAEIGADEGADYGAA4AAAAAfgYAJwYAzAYADgAAAABBBgAxBgAvBgAUAAAAAEgGACcGADEGAMwGADIGAAsAAAAAqQYARAYAFAAAAAAnBgBEBgBFBgAnBgBEBgAOAAAAACcGADMGACoGABEAAAAAJwYASAYARAYAJwYACwAAAAAvBgBIBgAOAAAAAEEGAEIGADcGABQAAAAALgYARAYAJwYAQQYANAYAGgAAAAAuBgAnBgBGBgBIBgAnBgAvBgBHBgAUAAAAACcGADkGAEQGACcGAEUGAA4AAAAAKAYASAYALwYADgAAAAA0BgBIBgAvBgARAAAAAEYGADQGAC8GAEcGABEAAAAANgYAJwYARQYARgYADgAAAAAoBgDMBgAqBgAOAAAAAC0GAMwGAEEGABEAAAAAKAYASAYALwYARwYAEQAAAAAxBgDMBgAnBgBEBgARAAAAAEgGACcGAEIGADkGAA4AAAAAfgYASAYARAYADgAAAAA0BgAvBgBHBgAUAAAAACcGADUGAEgGAEQGACcGABEAAAAALwYAJwYALwYARwYACwAAAADMBgAnBgARAAAAADQGACcGAEcGAC8GAA4AAAAARQYAzAYARAYAEQAAAAAoBgBGBgAvBgBHBgAUAAAAAC8GAMwGAK8GADEGAMwGABEAAAAANAYALgYANQYAzAYAEQAAAACpBgBGBgDMBgAvBgALAAAAACgGADEGAA4AAAAAJwYArwYAMQYAEQAAAAB+BgBIBgBEBgDMBgAOAAAAACwGAMwGACgGABcAAAAAfgYAMQYASAYARgYALwYARwYAIAAAAACpBgDMBgBBBgAxBgAuBgBIBgAnBgAzBgAqBgAaAAAAAC8GACcGAC8GAEYGACcGAEUGAEcGABQAAAAAMwYAQQYAJwYAMQYANAYAFAAAAABGBgCpBgAxBgAvBgBHBgAUAAAAACsGACcGAEYGAMwGACcGABcAAAAAKAYAMQYALgYARAYAJwYAQQYAFAAAAAAsBgAnBgAoBgAsBgAnBgAUAAAAAEUGAEIGACcGAEUGAMwGABQAAAAAKgYAOQYAzAYAzAYARgYAFAAAAAA1BgAnBgAvBgAxBgBHBgAOAAAAAKkGADMGAMwGABQAAAAAKgYANAYAqQYAzAYARAYADgAAAAA6BgDMBgAxBgARAAAAACwGAEUGAEQGAEcGABEAAAAALwYASAYARAYAKgYAEQAAAAAvBgBBBgAqBgAxBgARAAAAADQGAEYGAEgGAC8GABEAAAAANAYASAYARgYALwYAFAAAAABFBgAzBgAqBgBGBgAvBgALAAAAAEcGAEUGABcAAAAAQgYANgYAJwYAzAYAzAYARwYAFwAAAABCBgAnBgBGBgBIBgBGBgDMBgAaAAAAAEIGACcGAEYGAEgGAEYGAMwGAAwGABEAAAAANgYAJwYAKAYANwYAFAAAAAAnBgBEBgAoBgAqBgBHBgAUAAAAADEGADMGACcGAEYGAEcGAA4AAAAARgYARQYAzAYAEQAAAAA0BgAxBgA5BgDMBgAOAAAAADMGAEgGAMwGAA4AAAAAQgYASAYARwYAEQAAAAAoBgBHBgAqBgAxBgALAAAAAH4GAMwGABEAAAAArwYAzAYAMQYAzAYADgAAAADMBgCpBgDMBgARAAAAACgGACcGAMwGAC8GABEAAAAAQgYAJwYANgYAzAYAEQAAAAAqBgBFBgAnBgBFBgAXAAAAACcGAC4GAEQGACcGAEIGAMwGABQAAAAAKwYAJwYARAYAKwYAJwYAEQAAAABIBgBCBgAqBgDMBgARAAAAADQGACcGAKkGAMwGAAUAAABkCwAAAAAnBgDMBgAdAAAAAH4GACcGADMGAC4GAK8GAEgGAMwGAMwGABEAAAAANQYAJwYALwYAMQYAEQAAAABFBgAxBgAvBgBFBgAOAAAAAEIGAC8GADEGABEAAAAALgYAJwYANQYAzAYACwAAAABHBgAxBgARAAAAAEEGADYGACcGAMwGAAsAAAAAJwYASAYAIAAAAAAuBgAoBgAxBgBGBgCvBgAnBgAxBgAnBgBGBgAOAAAAADkGADEGADYGABQAAAAALQYAJwYANAYAzAYARwYAFAAAAABFBgAxBgAtBgBEBgBHBgALAAAAACoGACcGABEAAAAARQYANwYAMQYALQYAFAAAAACpBgAxBgAvBgBGBgAvBgAOAAAAACcGADUGAEQGAA4AAAAAMwYAzAYARwYADgAAAABHBgBFBgBHBgAUAAAAAEIGACcGAEYGAEgGAEYGABQAAAAAqQYARgYAJwYAzAYARwYAEQAAAAAvBgAnBgA0BgAqBgAUAAAAAEUGACoGAEcGAEUGAMwGAA4AAAAARgYAJwYARQYADgAAAACpBgAxBgAvBgAXAAAAAC8GACcGAC8GAK8GACcGAEcGABQAAAAAOQYARQYASAYARQYAzAYAFAAAAABFBgBGBgAqBgA0BgAxBgARAAAAADEGAEgGADIGAMwGAA4AAAAARQYAKgYARgYAEQAAAAAiBgBGBgBHBgAnBgAUAAAAAEYGACgGACcGADQGAC8GABEAAAAAOQYARAYARgYAzAYAHQAAAABFBgDMBgAMIAAuBgBIBgAnBgAzBgAqBgAUAAAAACcGADcGAEQGACcGADkGABEAAAAAJwYAMwYAKgYADAYAEQAAAABHBgBFBgDMBgBGBgALAAAAACoGADEGAA4AAAAANQYAQQYAKgYAEQAAAACpBgAnBgBFBgBEBgARAAAAADUGAEgGADEGAMwGABQAAAAAfgYAMQYARwYAzAYAMgYADgAAAACpBgBGBgAvBgAUAAAAAEYGAK8GADEGACcGAEYGAA4AAAAAMAYAqQYAMQYADgAAAABGBgDMBgAyBgAaAAAAAH4GAMwGADQGACcGAH4GAMwGADQGABoAAAAAfgYAMQYAMwYANAYARwYAJwYAzAYAGgAAAABFBgAtBgCpBgBIBgBFBgDMBgAqBgAdAAAAAC8GACcGAC8GAEYGACcGAEUGAEcGAAwGACYAAAAARQYAzAYADCAAKgYASAYAJwYARgYAMwYAKgYARgYALwYADgAAAACGBgBIBgBGBgARAAAAAC0GACcGADYGADEGABQAAAAAKAYASAYALwYARgYALwYAFAAAAAAtBgBCBgBIBgBCBgDMBgARAAAAADUGADEGAMwGAC0GABoAAAAAJwYAMwYAKgYAQQYAJwYALwYARwYAGgAAAABFBgAzBgAqBgBGBgAvBgAnBgAqBgAOAAAAADEGAEgGAMwGABEAAAAALQYAqQYARQYADAYAEQAAAAAzBgAnBgAyBgDMBgAXAAAAAEcGAEUGAKkGACcGADEGAMwGABEAAAAAJwYAMwYAJwYAMwYAFwAAAABFBgDMBgAMIACpBgBGBgBFBgAXAAAAAC8GACcGADQGACoGAEYGAC8GABcAAAAARgYAqQYAMQYALwYARgYALwYADgAAAABHBgAnBgDMBgAXAAAAAEcGAEUGADEGACcGAEcGAMwGABQAAAAAIgYARQYAJwYALwYARwYAEQAAAAAzBgAnBgAoBgBCBgAXAAAAAEYGACcGAK8GADIGAMwGADEGABQAAAAAMQYAOQYAJwYAzAYAKgYAFwAAAAAzBgAuBgBGBgCvBgBIBgDMBgARAAAAADUGAEgGADEGACoGAAsAAAAAKAYAJwYAHQAAAAAxBgAzBgAnBgBGBgBHBgAMIABHBgAnBgALAAAAAEcGACcGAAsAAAAAOgYANAYAFAAAAAA4BgAnBgBHBgAxBgAnBgAdAAAAAEUGAC0GAKkGAEgGAEUGAMwGACoGADQGABEAAAAASAYAqQYAzAYARAYAFwAAAACvBgAxBgBIBgCvBgAnBgBGBgAXAAAAAC4GAMwGACcGAEYGACoGAMwGABEAAAAAMQYASAYANAYARgYAFwAAAAB+BgDMBgAxBgBIBgAyBgDMBgAXAAAAAC8GADQGAEgGACcGADEGAMwGABcAAAAALAYASAYAMwYAJwYAMgYAzAYAFAAAAAB+BgBGBgBHBgAnBgBGBgAUAAAAACoGAC8GACcGAEgGAEUGABEAAAAAOQYARAYAzAYARQYAEQAAAAAvBgAnBgBGBgBFBgAOAAAAAC0GACcGAEQGABEAAAAAhgYAzAYAMgYAzAYAFwAAAAA0BgBBBgAnBgBBBgDMBgAqBgAOAAAAACcGAEUGACcGABQAAAAARgYAqQYAMQYALwYARQYADgAAAAAtBgAoBgAzBgARAAAAAEUGACgGAEYGACcGABQAAAAAKgYALAYAMgYAzAYARwYAFAAAAAA3BgBEBgAoBgAnBgBGBgARAAAAADcGAEQGACgGAEUGABQAAAAARgYARwYAJwYAzAYAzAYAFAAAAABGBgCpBgBGBgBGBgAvBgAOAAAAACgGACcGADEGABQAAAAANAYARwYAJwYALwYAKgYADgAAAAA1BgBEBgAtBgAaAAAAACcGAEYGAEIGAEQGACcGACgGAAwGABEAAAAAfgYAzAYANAYARwYAFAAAAAAqBgAtBgAxBgDMBgBFBgAaAAAAAC0GAC8GACcGAKkGACsGADEGAMwGABcAAAAARQYAKAYAJwYAMQYAMgYARwYAEQAAAACpBgA0BgBIBgAxBgAOAAAAACwGAEYGAK8GABQAAAAAJwYALwYAJwYARQYARwYAEQAAAACpBgBGBgAnBgAxBgAOAAAAAKkGAEYGAEUGABQAAAAAQgYANgYAJwYASAYAKgYAFwAAAAAuBgAvBgBFBgAnBgAqBgDMBgARAAAAAKkGAEYGAEYGAC8GABcAAAAANAYAMQYARQYARgYALwYARwYADgAAAACpBgBEBgDMBgAUAAAAACcGAEUGADEGAEgGADIGABcAAAAAJwYAOQYAKgYALwYAJwYARAYAFAAAAABHBgAzBgAqBgBGBgAvBgAUAAAAACIGAEYGAK8GACcGAEcGAA4AAAAARAYAOgYASAYAFAAAAAAyBgBGBgAvBgAnBgBGBgARAAAAACgGACcGAEEGAMwGABcAAAAANwYARAYAKAYAJwYARgYADAYAFAAAAAAzBgAnBgBIBgAnBgCpBgAXAAAAAH4GADEGAC8GACcGAC4GACoGABoAAAAAfgYAzAYANAYARgYARwYAJwYALwYAFwAAAAAuBgAvBgAnBgBIBgBGBgAvBgAOAAAAAEUGAEQGACoGABQAAAAANAYAMQYAJwYAzAYANwYAFAAAAABGBgDMBgAzBgAqBgBFBgAOAAAAAKkGADQGAEUGABEAAAAALQYAqQYAzAYARQYADgAAAAAvBgBIBgA0BgAUAAAAAEcGADIGAMwGAEYGAEcGABcAAAAARgYALwYAJwYAMQYARgYALwYAFAAAAABFBgDMBgCpBgBGBgBFBgARAAAAAFMAAHUAAGIAADEAAA4AAAAAJwYASAYARAYADgAAAABBBgA1BgBEBgAOAAAAADIGAMwGADEGABQAAAAAUwAAdQAAYgAAMQAAMQAAFAAAAABTAAB1AABiAAAxAAAyAAAOAAAAAC8GAEgGAEUGABcAAAAAUwAAZQAAYwAAbwAAbgAAZAAADwkAALkIAAACBQACABEAAgAmAAIAHgACAA0AAgAlAAIAIQACAAwAAgAgAAIAKwACACwAAgAKAAIAKAACADAAAgAfAAIACAACAA8AEwACACkAAgAJAAIANAAPAAIAEAACABUAAgAzAAIAMQACADgAAgAcAAIALgACAAgAAgASAAIAKgACAAQAAgAnAAIANQACADIABgACABgAAgAcAAIACwACAAgAAgAOAAIAFAACAC8AAgAXAAIAOAACACMAAgAYAAIAHQACAAgAAgAZAAIAGgACABYAAgAiAAIAGAACACQAAgA2AAIALQACABsAAgASAAIABwA3AEUANwACABQAAgAvAAIAYwACACcAAgBSAAIADQACAE8AAgBDAAIAUAACABgAAgBaAAIATQACAEQAAgAYAAIAVgACAD8AAgBPAAIAQwACADwAAgA7AAIARAA3AAIAFAACAFMAAgBCAAIAYQACAAgAAgANAAIAGQACAD0AAgA5AAIAEgACAEwAAgBUAAIAXQACACcAAgA6AAIARAACAAgAAgAMAAIAQAACAFwAAgA+AAIAVwACAFUAAgAYAAIAMwACACcAAgANAAIAGQACAEYAAgA6AAIAHAACADsAAgAtAAIAGAACABwAAgBHAAIAXwACAC8AAgA+AAIAWQACABgAAgBOAAIAUQACAC0AAgAYAAIAJwACAFIAAgAZAAIADAACAGIAAgBbAAIAWAACAEkAAgBbAAIAQQACAE0AAgBEAAIANwA3ADcAAgAIAAIAYAACAEgAAgBLAAIASgACAF4ANwBoADcAAgAcAAIAaQACAGQAAgAYAAIAZQACABgAAgAKAAIAbQACAGYAAgAzAAIAbgACABoAAgAMAAIAMwACAGsAAgBnAAIALQACABgAAgAzAAIAawACAGwAAgAYAAIAagACAE0AAgBEAAIANwA3ADcAAgAIAAIAYAACAEgAAgBLAAIASgACAF4ANwCKADcAAgCIAAIAYwACAG8AAgBVAAIAdgACAAwAAgB0AAIAcAACAHkAAgANAAIAcQACAHQAAgANAAIAcwACACkAAgAJAAIARAACAAgAAgB3AAIAcAACAHoAAgB3AAIAcAACAH8AAgAYAAIAdwACAHAAAgCJAAIARAACABgAAgCGAAIADQACAIAAAgByAAIAGAACAIEAAgB4AAIAgwACAIQAAgBMAAIANwA3ADcAAgAYAAIAfAACAIsAAgB7AAIAGAACAIwAAgAYAAIAhwACABgAAgB9AAIAdwACAIUAAgASAAIAdQACAIIAAgANAAIALwACAH4AAgBMAAIANwA3ADcAjQBfAAIALwACAMwAAgAcAAIA0gACAC0AAgCrAAIAtQACAMkAAgC/AAIAZAACABgAAgDHAAIAFAACAJUAAgCoAAIAOAACALAAAgCRAAIAqQACAEwAAgCbAAIAnwACAMgAAgBMAAIAlAACAAgAAgAUAAIAlgACANsAAgAyADcAAgDeAAIAHAACANIAAgCPAAIAxAACAAwAAgCgAAIAvQACAJcAAgBEAAIAGAACAAwAAgCBAAIAeAACAHcAAgCYAAIAzQACALkAAgAcAAIArQACAMEAAgANAAIAqgACAAgAAgAvAAIAYwACAJwAAgBVAAIAsQACAH0AAgDaAAIADQACALoAAgClAAIAWwACAA4AAgAUAAIAmgACADUAAgC3AAIAzwACABgAAgDWAAIA0wACAIEAAgB4AAIACAACANwAAgCvAAIAoQACABoAAgDVAAIAuAACABgAAgAMAAIA1wACALYAAgANAAIAugACAKUAAgAFAAIAEQACALcAAgCjAAIADQACALQAAgAPABMAAgApAAIACQAPAAIAOAACAFsAAgDGAAIAEgACAKYAAgAIAAIAogACAI4AAgDFAAIAswACAA0AAgCeAAIASwACADcANwA3AAIANwACABQAAgCnAAIArgACALsAAgAVAAIAlwACAH0AAgDQAAIAkwACAAgAAgDYAAIAewACAGMAAgDRAAIAGAACAMsAAgDOAAIAwAACABQAAgCnAAIAwgACAHUANwACALIAAgDZAAIAGQACAJIAAgCZAAIAygACAJ0AAgAIAAIAhwACANQAAgANAAIAvgACAKQAAgBLAAIACAACAKwAAgC8AAIACgACAN0AAgAaAAIAkAACADYAAgDDADcAjQDpAAIAFAACAC8AAgAUAQIAYAACAO8AAgBfAAIA6wACAEQAAgAcAAIAEQECABsBAgDrAAIA+wACAPkAAgAEAQIAGAACAOoAAgANAAIAkQACAOUAAgAaAQIAmwACAOEAAgBMAAIAHAACAAwAAgATAQIAGAACAHIAAgAYAAIAKQACAAkAAgAYAAIATwACAEMAAgAzAAIA4AACAO0AAgAYAAIABwECADgAAgADAQIACAACADgAAgD9AAIANgACAC0AAgANAAIA7gACABQAAgAPAQIAmwACAP4AAgDYAAIA8AACAPEAAgAYAAIAuwACAPwAAgA4AAIACwECAPoAAgDaAAIAMwACAAUBAgAVAQIAGAACABkBAgCgAAIArAACABoAAgAQAQIAEgACAAEBAgA3ADcANwACABwAAgAvAAIA7gACABoAAgAUAAIA/wACAAwBAgA4AAIA+AACABQAAgDmAAIA3wACAIQAAgDwAAIADgECABQAAgAAAQIAJAACADgAAgD3AAIAGAACABkBAgDiAAIAOAACAHIAAgAIAQIAEgACAOgAAgAYAAIA2AACAKAAAgDjAAIALwACAPUAAgAaAAIAFQACAF8AAgAYAQIAEgACABYBAgDsAAIAkQACABoAAgAMAAIA9gACABgAAgACAQIA8wACABIAAgDyAAIACAACAF8AAgDMAAIA5AACABgAAgAGAQIADQECAAIBAgD0AAIACAACAIcAAgDzAAIAEgECABcBAgAYAAIA5wACABgAAgAKAQIAkQACAAkBNwATAAAAAo0AHwECAB4BAgAdAQIAFwAAAAKNAB8BAgAfAQIAHgECAB0BAgAbAAAAAo0AHwECACIBAgAfAQIAHgECAB0BAgANAAAAAo0AHgECACIB';
  book64 =
      'AAAEAAAAERUAABQAAAAAQgAAbwAAbwAAawAAMQAAFAAAAAAnBgBIBgBEBgDMBgBGBgARAAAAAKkGACoGACcGACgGAA4AAAAAQQYANQYARAYACAAAAAAgAAAOAAAAADQGAEgGAEUGABEAAAAAMQYAzAYAzAYAMwYACwAAAAAoBgBHBgARAAAAACcGAEgGAMwGAEYGAAsAAAAARgYARwYAFwAAAAAnBgBGBgBCBgBEBgAnBgAoBgARAAAAACoGAEQGACcGADQGABEAAAAAKAYAMQYAJwYAzAYAGgAAAAAuBgBIBgA0BgAtBgAnBgBEBgBFBgARAAAAAEYGADQGACcGAEYGABEAAAAAKgYARgYARwYAJwYAFwAAAABCBgAxBgAoBgAnBgBGBgDMBgALAAAAAMwGAKkGAA4AAAAALQYAKgYAzAYAEQAAAAAuBgBIBgAvBgA0BgALAAAAAEUGAMwGABQAAAAAKgYASAYAJwYARgYALwYACAAAAAAuAAAUAAAAAEUGADkGADEGAEEGAMwGAA4AAAAALgYASAYALwYACAAAAAAiAAALAAAAAC8GADEGABQAAAAAJwYAKgYARwYAJwYARQYAFAAAAAAvBgAnBgA0BgAqBgBHBgARAAAAAK8GAEEGACoGADoAAAsAAAAAIgYARgYAFwAAAABEBgAtBgA4BgAnBgAqBgDMBgARAAAAACgGAEgGAC8GAEYGABEAAAAALQYAMwYAzAYARgYAEQAAAABFBgBCBgAnBgBFBgAXAAAAAEEGADEGAMwGAC8GAEgGAEYGABEAAAAALwYASAYAMwYAKgYAEQAAAAAoBgAnBgA0BgAvBgALAAAAACcGAEUGAAsAAAAAJwYAMgYAFAAAAAAsBgBFBgBHBgBIBgAxBgALAAAAAEUGAEYGAAgAAAAASAYACwAAAACpBgBHBgARAAAAAKkGADEGAC8GAEcGAA4AAAAALQYAqQYARQYACAAAAAAhAAAOAAAAACcGAMwGAEYGAA4AAAAAQgYAKAYARAYAFAAAAABGBgA4BgAnBgBFBgDMBgARAAAAAEYGACgGAEgGAC8GABoAAAAAJwYAzAYARgYALAYAJwYARgYAKAYAFwAAAACrAAAnBgAsBgAxBgAnBgDMBgAUAAAAACgGADEGACcGAC8GADEGABQAAAAARQYAMgYAzAYAKgYAzAYACwAAAAAxBgAnBgAOAAAAAEcGAMwGAIYGAA4AAAAALwYAJwYALwYAFAAAAAAnBgA5BgBEBgAnBgBFBgAUAAAAAC4GAEQGACcGAEEGADQGABEAAAAANAYAJwYARwYALwYAFwAAAAB+BgAxBgBIBgBGBgAvBgBHBgAOAAAAACcGAK8GADEGAA4AAAAALQYAMQYAQQYAEQAAAACpBgBGBgDMBgAvBgARAAAAAC8GACcGAC8GAEcGABQAAAAALwYAzAYArwYAMQYAzAYADgAAAAA0BgAvBgBHBgALAAAAAC8GAEgGABQAAAAALwYAMQYAqQYAJwYAMQYADgAAAABBBgBCBgA3BgAOAAAAADIGAC8GAEcGABQAAAAASAYAJwYAMQYAzAYAMgYACwAAAACpBgBEBgAOAAAAAEEGADEGAC8GAA4AAAAAQgYAMQYANgYAEQAAAAAoBgBGBgAvBgBHBgAOAAAAACgGAMwGACoGABEAAAAANgYAJwYARQYARgYADgAAAABFBgDMBgBEBgARAAAAACgGAEgGAC8GAEcGABQAAAAAJwYARAYARQYAJwYARAYAEQAAAAA0BgAuBgA1BgDMBgAOAAAAAH4GAEgGAEQGABEAAAAARgYANAYALwYARwYAEQAAAAAnBgBIBgBEBgAnBgARAAAAAH4GAEgGAEQGAMwGAAsAAAAAKAYAMQYADgAAAAB+BgAnBgDMBgARAAAAAEgGACcGAEIGADkGAA4AAAAAJwYAMwYAKgYADgAAAABGBgBBBgAxBgAUAAAAAEYGACgGAEgGAC8GAEcGABEAAAAAMQYAzAYAJwYARAYACwAAAADMBgAnBgAOAAAAADQGAEgGAC8GABQAAAAAJwYANQYASAYARAYAJwYADgAAAAAsBgDMBgAoBgAaAAAAAC4GACcGAEYGAEgGACcGAC8GAEcGAA4AAAAAKAYASAYALwYADgAAAAAtBgDMBgBBBgAUAAAAAEYGAKkGADEGAC8GAEcGABQAAAAAKwYAJwYARgYAzAYAJwYAFwAAAAAoBgAxBgAuBgBEBgAnBgBBBgAUAAAAADMGAEEGACcGADEGADQGABQAAAAARQYAQgYAJwYARQYAzAYAFAAAAAAsBgAnBgAoBgAsBgAnBgAUAAAAADUGACcGAC8GADEGAEcGACAAAAAAqQYAzAYAQQYAMQYALgYASAYAJwYAMwYAKgYAFAAAAAAqBgA5BgDMBgDMBgBGBgAaAAAAAC8GACcGAC8GAEYGACcGAEUGAEcGAA4AAAAAqQYAMwYAzAYAEQAAAABIBgBCBgAqBgDMBgARAAAAACgGAEcGACoGADEGABcAAAAAQgYAJwYARgYASAYARgYAzAYAFwAAAABCBgA2BgAnBgDMBgDMBgBHBgAUAAAAADEGADMGACcGAEYGAEcGABEAAAAALwYAQQYAKgYAMQYADgAAAADMBgCpBgDMBgARAAAAAK8GAMwGADEGAMwGABQAAAAAKgYANAYAqQYAzAYARAYAEQAAAAA0BgBGBgBIBgAvBgAaAAAAAEIGACcGAEYGAEgGAEYGAMwGAAwGABQAAAAARQYAMwYAKgYARgYALwYAEQAAAABCBgAnBgA2BgDMBgARAAAAAC8GAEgGAEQGACoGAAsAAAAAfgYAzAYADgAAAABGBgBFBgDMBgARAAAAADYGACcGACgGADcGAAsAAAAARwYARQYADgAAAAA6BgDMBgAxBgAXAAAAACcGAC4GAEQGACcGAEIGAMwGABEAAAAANAYASAYARgYALwYAEQAAAAA0BgAnBgCpBgDMBgAUAAAAACcGAEQGACgGACoGAEcGABEAAAAAKgYARQYAJwYARQYADgAAAABCBgBIBgBHBgARAAAAACgGACcGAMwGAC8GABEAAAAANAYAMQYAOQYAzAYAEQAAAAAsBgBFBgBEBgBHBgAOAAAAADMGAEgGAMwGABQAAAAAKwYAJwYARAYAKwYAJwYABQAAAGQRAAAAAKkGACcGAEUGAEQGACYAAAAARQYAzAYADCAAKgYASAYAJwYARgYAMwYAKgYARgYALwYAHQAAAAAvBgAnBgAvBgBGBgAnBgBFBgBHBgAMBgALAAAAACgGACcGABQAAAAARQYARgYAKgYANAYAMQYAEQAAAAAiBgBGBgBHBgAnBgARAAAAADUGAEgGADEGACoGABQAAAAALQYAQgYASAYAQgYAzAYAEQAAAAA1BgAxBgDMBgAtBgAUAAAAAEUGACoGAEcGAEUGAMwGABcAAAAARQYAzAYADCAAqQYARgYARQYAFwAAAAAvBgAnBgA0BgAqBgBGBgAvBgAUAAAAAEYGAK8GADEGACcGAEYGABoAAAAAJwYAMwYAKgYAQQYAJwYALwYARwYADgAAAAAzBgDMBgBHBgAOAAAAACcGADUGAEQGABoAAAAARQYALQYAqQYASAYARQYAzAYAKgYAEQAAAABFBgAxBgAvBgBFBgAOAAAAAEYGACcGAEUGABEAAAAAJwYAMwYAJwYAMwYAHQAAAABFBgAtBgCpBgBIBgBFBgDMBgAqBgA0BgAUAAAAAKkGAEYGACcGAMwGAEcGABQAAAAAQgYAJwYARgYASAYARgYAHQAAAABFBgDMBgAMIAAuBgBIBgAnBgAzBgAqBgARAAAAAC4GACcGADUGAMwGAAsAAAAARwYAMQYAEQAAAAAzBgAnBgAyBgDMBgAOAAAAAEcGACcGAMwGABQAAAAAJwYANwYARAYAJwYAOQYAGgAAAABFBgAzBgAqBgBGBgAvBgAnBgAqBgAdAAAAAH4GACcGADMGAC4GAK8GAEgGAMwGAMwGABEAAAAALQYAJwYANgYAMQYAFwAAAABGBgCpBgAxBgAvBgBGBgAvBgARAAAAADUGAEgGADEGAMwGABcAAAAAMwYALgYARgYArwYASAYAzAYAFAAAAAAxBgA5BgAnBgDMBgAqBgARAAAAACcGADMGACoGAAwGABQAAAAARQYAMQYALQYARAYARwYADgAAAABFBgAqBgBGBgAgAAAAAC4GACgGADEGAEYGAK8GACcGADEGACcGAEYGAA4AAAAAhgYASAYARgYAHQAAAAAxBgAzBgAnBgBGBgBHBgAMIABHBgAnBgAUAAAAAC0GACcGADQGAMwGAEcGABcAAAAARgYAJwYArwYAMgYAzAYAMQYAFAAAAAAiBgBFBgAnBgAvBgBHBgAOAAAAADkGADEGADYGABEAAAAARwYARQYAzAYARgYAEQAAAAAxBgBIBgAyBgDMBgALAAAAADoGADQGABEAAAAARQYANwYAMQYALQYAEQAAAAA5BgBEBgBGBgDMBgAOAAAAAEIGAC8GADEGABEAAAAALwYAJwYANAYAKgYADgAAAABGBgDMBgAyBgALAAAAAEcGACcGABcAAAAARwYARQYAqQYAJwYAMQYAzAYAFAAAAAB+BgAxBgBHBgDMBgAyBgALAAAAACcGAMwGABEAAAAANQYAJwYALwYAMQYAFAAAAACpBgAxBgAvBgBGBgAvBgALAAAAACcGAEgGABQAAAAARgYAKAYAJwYANAYALwYADgAAAACpBgBGBgAvBgAaAAAAAH4GADEGADMGADQGAEcGACcGAMwGABcAAAAALwYAJwYALwYArwYAJwYARwYACwAAAAAqBgAxBgARAAAAAC0GAKkGAEUGAAwGABEAAAAAMwYAJwYAKAYAQgYACwAAAAAqBgAnBgAaAAAAAH4GAMwGADQGACcGAH4GAMwGADQGAA4AAAAARwYARQYARwYADgAAAAAwBgCpBgAxBgAUAAAAACgGAEgGAC8GAEYGAC8GAA4AAAAAqQYAMQYALwYAFAAAAAA4BgAnBgBHBgAxBgAnBgAUAAAAADkGAEUGAEgGAEUGAMwGABEAAAAASAYAqQYAzAYARAYADgAAAAA1BgBBBgAqBgARAAAAAEEGADYGACcGAMwGABcAAAAARwYARQYAMQYAJwYARwYAzAYADgAAAAAxBgBIBgDMBgAXAAAAAC8GADQGAEgGACcGADEGAMwGAA4AAAAANQYARAYALQYAFAAAAABFBgDMBgCpBgBGBgBFBgAXAAAAAEYGAC8GACcGADEGAEYGAC8GABEAAAAAKAYAJwYAQQYAzAYAEQAAAAAtBgCpBgDMBgBFBgAUAAAAADMGACcGAEgGACcGAKkGAA4AAAAAqQYARAYAzAYAFwAAAAB+BgDMBgAxBgBIBgAyBgDMBgAUAAAAACoGAC0GADEGAMwGAEUGABcAAAAAJwYAOQYAKgYALwYAJwYARAYAFwAAAABFBgAoBgAnBgAxBgAyBgBHBgAXAAAAAC4GAMwGACcGAEYGACoGAMwGABQAAAAARgYAzAYAMwYAKgYARQYAEQAAAACpBgBGBgBGBgAvBgAaAAAAACcGAEYGAEIGAEQGACcGACgGAAwGABEAAAAARQYAKAYARgYAJwYADgAAAACpBgBGBgBFBgAUAAAAAEcGADMGACoGAEYGAC8GAA4AAAAARQYARAYAKgYAFAAAAABGBgCpBgAxBgAvBgBFBgAUAAAAAH4GAEYGAEcGACcGAEYGABEAAAAANwYARAYAKAYARQYAGgAAAAAtBgAvBgAnBgCpBgArBgAxBgDMBgAOAAAAAC8GAEgGADQGABQAAAAAKgYALAYAMgYAzAYARwYAFwAAAAA0BgBBBgAnBgBBBgDMBgAqBgARAAAAAH4GAMwGADQGAEcGAA4AAAAALQYAKAYAMwYAFwAAAACvBgAxBgBIBgCvBgAnBgBGBgAUAAAAAEYGAKkGAEYGAEYGAC8GAA4AAAAAqQYANAYARQYADgAAAAAtBgAnBgBEBgAXAAAAACwGAEgGADMGACcGADIGAMwGABQAAAAAJwYARQYAMQYASAYAMgYAFAAAAAAqBgAvBgAnBgBIBgBFBgAUAAAAADQGADEGACcGAMwGADcGAA4AAAAAJwYARQYAJwYAEQAAAACpBgBGBgAnBgAxBgARAAAAADEGAEgGADQGAEYGABQAAAAAQgYANgYAJwYASAYAKgYAFAAAAAAnBgAvBgAnBgBFBgBHBgAOAAAAACgGACcGADEGABQAAAAARgYARwYAJwYAzAYAzAYADgAAAAAsBgBGBgCvBgAUAAAAAEcGADIGAMwGAEYGAEcGABcAAAAANwYARAYAKAYAJwYARgYADAYAFAAAAAA0BgBHBgAnBgAvBgAqBgARAAAAAKkGADQGAEgGADEGABcAAAAAfgYAMQYALwYAJwYALgYAKgYAFwAAAAAuBgAvBgAnBgBIBgBGBgAvBgARAAAAADkGAEQGAMwGAEUGABQAAAAANwYARAYAKAYAJwYARgYAFAAAAAAiBgBGBgCvBgAnBgBHBgAXAAAAADQGADEGAEUGAEYGAC8GAEcGABcAAAAALgYALwYARQYAJwYAKgYAzAYADgAAAABEBgA6BgBIBgARAAAAAIYGAMwGADIGAMwGABQAAAAAMgYARgYALwYAJwYARgYAEQAAAAAvBgAnBgBGBgBFBgAaAAAAAH4GAMwGADQGAEYGAEcGACcGAC8GABEAAAAAUwAAdQAAYgAAMQAADgAAAAAyBgDMBgAxBgAOAAAAACcGAEgGAEQGABQAAAAAUwAAdQAAYgAAMQAAMQAAFAAAAABTAAB1AABiAAAxAAAyAAAOAAAAAC8GAEgGAEUGABoAAAAAQwAAaAAAYQAAcAAAdAAAZQAAcgAAFwAAAABTAABlAABjAABvAABuAABkAAAUAAAAAFMAAFUAAEIAADIAADEAABEAAAAAMwYARAYAJwYARQYAEQAAAABFBgDMBgAnBgBFBgARAAAAAC8GACcGADEGAEUGAAsAAAAAMQAAMQAAEQAAAABTAABVAABCAAAyAAARAAAAAGgAAGUAAGwAAG8AABcAAAAAUwAAVQAAQgAAMgAAMQAAMgAAFAAAAABTAABVAABCAAAyAAAyAAApCQAAuQgAAAIhAAQAIwAEAB8ABAAwAAQAJwAEABcABAAYAAQABwAEAAgABAAdAAQANAAEAC0ABAAzAAQADgAEADkABAArAAQAGQA1AAQABgAEACgABAAgABkABAAJAAQADwAEADgABAA2AAQADAAEACkABAAyAAQAKwAEABQABAAVAAQAEwAEABEABAAbAAQAJQAuAAQAKgAEACkABAANAAQAKwAEABIABAAaAAQALwAEACIABAAMAAQACgAEACoABAAxAAQAKwAEAB4ABAA3AAQAJAAEABwABAAqAAQACwAEACwABAAmAAQAEAAEABQABAAFABYAVQAWAAQAGgAEAC8ABAA9AAQAEQAEAF0ABAAnAAQATQAEAFEABABkAAQAKgAEAE8ABABUAAQAWgAEACoABABgAAQAWAAEAE0ABABRAAQARQAEAFwABABaABYABAAaAAQAWQAEAEkABABWAAQAKwAEACcABAAeAAQAPwAEAEcABAAUAAQAXwAEAFMABABSAAQAEQAEAFsABABaAAQAKwAEAAcABABKAAQAQgAEAEsABABBAAQAQwAEACoABAA4AAQAEQAEACcABAAeAAQARAAEAFsABAApAAQAXAAEACYABAAqAAQAKQAEAEYABABXAAQALwAEAEsABAA8AAQAKgAEAE4ABABQAAQAJgAEACoABAARAAQAXQAEAB4ABAAHAAQAYQAEAEwABABeAAQAYgAEAEwABABIAAQAVAAEAFoABAAWABYAFgAEACsABAA+AAQAOwAEAGMABAA6AAQAQAAWAGYAFgAEACkABABnAAQAbAAEACoABABuAAQAKgAEAC0ABABrAAQAaAAEADgABABvAAQANwAEAAcABAA4AAQAaQAEAGUABAAmAAQAKgAEADgABABpAAQAbQAEACoABABqAAQAVAAEAFoABAAWABYAFgAEACsABAA+AAQAOwAEAGMABAA6AAQAQAAWAI0AFgAEAIcABAA9AAQAeAAEAEMABAB7AAQABwAEAHkABACCAAQAcgAEACcABACLAAQAeQAEACcABAB1AAQABgAEACgABABaAAQAKwAEAIEABACCAAQAegAEAIEABACCAAQAigAEACoABACBAAQAggAEAIMABABaAAQAKgAEAIkABAAnAAQAjAAEAH0ABAAqAAQAiAAEAHMABAB+AAQAdwAEAF8ABAAWABYAFgAEACoABACGAAQAcAAEAIAABAAqAAQAhQAEACoABAB8AAQAKgAEAHQABACBAAQAdgAEABQABACEAAQAcQAEACcABAAvAAQAfwAEAF8ABAAWABYAFgCOAFcABAAvAAQAogAEACkABAC7AAQAJgAEALUABACPAAQA0QAEAJEABABsAAQAKgAEAKwABAAaAAQA3QAEANoABAAMAAQAqwAEAKAABACTAAQAXwAEANMABACdAAQA3wAEAF8ABACoAAQAKwAEABoABADLAAQAvwAEACUAFgAEANsABAApAAQAuwAEAK0ABACWAAQABwAEANUABADOAAQAtgAEAFoABAAqAAQABwAEAIgABABzAAQAgQAEALwABACZAAQAmwAEACkABADMAAQAtwAEACcABAC+AAQAKwAEAC8ABAA9AAQAwAAEAEMABACzAAQAdAAEAMUABAAnAAQA1gAEAKEABABMAAQAEgAEABoABAC0AAQAGwAEAMcABACvAAQAKgAEALEABADSAAQAiAAEAHMABAArAAQA2QAEAKYABAClAAQANwAEALIABADNAAQAKgAEAAcABACVAAQAsAAEACcABADWAAQAoQAEACEABAAjAAQAxwAEAMMABAAnAAQA3AAEABkANQAEAAYABAAoABkABAAMAAQATAAEAJwABAAUAAQA2AAEACsABACkAAQAyAAEAJcABADQAAQAJwAEAJ4ABABjAAQAFgAWABYABAAWAAQAGgAEAM8ABADBAAQAxAAEAA8ABAC2AAQAdAAEAKoABACnAAQAKwAEAJIABACAAAQAPQAEAN4ABAAqAAQAxgAEAJoABACQAAQAGgAEAM8ABACuAAQAhAAWAAQAvQAEALgABAAeAAQAwgAEALkABACpAAQAygAEACsABAB8AAQAugAEACcABACfAAQAmAAEAGMABAArAAQAlAAEANQABAAtAAQAowAEADcABADJAAQALAAEANcAFgCOAAABBAAaAAQALwAEAAQBBAA+AAQA8AAEAFcABAD6AAQAWgAEACkABAAcAQQA4gAEAPoABAD3AAQA+wAEAO4ABAAqAAQAGQEEACcABACgAAQA9QAEAOMABADTAAQABwEEAF8ABAApAAQABwAEAPMABAAqAAQAfQAEACoABAAGAAQAKAAEACoABABNAAQAUQAEADgABADsAAQA9AAEACoABAACAQQADAAEABcBBAArAAQADAAEABABBAAsAAQAJgAEACcABAD8AAQAGgAEAOYABADTAAQADAEEAJIABAD5AAQAFAEEACoABADEAAQA6wAEAAwABAAYAQQA6QAEAMUABAA4AAQAFgEEAO0ABAAqAAQADQEEANUABACUAAQANwAEABEBBAAUAAQA8QAEABYAFgAWAAQAKQAEAC8ABAD8AAQANwAEABoABAAJAQQAGgEEAAwABADvAAQAGgAEAAMBBAD9AAQAdwAEAPkABAAOAQQAGgAEAAYBBAALAAQADAAEAOEABAAqAAQADQEEAOgABAAMAAQAfQAEAOoABAAUAAQAGwEEACoABACSAAQA1QAEAOAABAAvAAQACgEEADcABAAPAAQAVwAEAPgABAAUAAQA/wAEAAUBBACgAAQANwAEAAcABAAPAQQAKgAEAAgBBAALAQQAFAAEAPYABAArAAQAVwAEAKIABAABAQQAKgAEAOcABADkAAQACAEEAP4ABAArAAQAfAAEAAsBBAASAQQA5QAEACoABAATAQQAKgAEABUBBACgAAQA8gAWABMAAAACjgAeAQQAAwAEAB8BBAAXAAAAAo4AHgEEAB4BBAADAAQAHwEEABsAAAACjgAeAQQAIgEEAB4BBAADAAQAHwEEAA0AAAACjgADAAQAIgETAAAAAiYBBAApAAQAKAEEACcBBwAAAAErAdsAAAD/////////////AQAHAAAAAQAAAAAAAAAAAAAAAAIAEQAAAAIBAAQAAwAEAAIABAAHAAAAAQAAAQABAAAAAAAAAAEABwAAAAEdAQAABAAAAAAAAAABAAsAAAABJAEWACMBAgACAAAAAAAAAAEABwAAAAEgAQIAAwAAAAAAAAABAAcAAAABIQEDAAUAAAAAAAAAAQAHAAAAASUBAwD//////////wEABwAAAAEtAQYA//////////8BAAcAAAABLAEGAAYAAAAAAAAAAQALAAAAASoBFgApAQ==';
  cWhite = color(255, 255, 255, 255);
  cBlack = color(255, 0, 0, 255);
  cBlue = color(0, 0, 255, 255);
  font = await getFont('Zar.ttf');
  font = new Uint8Array(font);
  debugger;
  fontHeapPtr = copyBufferToHeap(font);
  fontSize = 42;
  bookbuf = base64ToBuffer(book64);

  let a = new book(bookbuf, 500, 500, font, 30, cWhite, cBlack);
  debugger;
  console.time('getListOfPageIndicators');
  let r1 = a.getListOfPageIndicators()
  console.timeEnd('getListOfPageIndicators');
  console.time('renders');
  a.renderNPages({group: 0, atom: 0}, r1.length);
  console.timeEnd('renders');

  let _1 = a.contentLength();
  for (let i = 0; i < _1; i++) console.log(a.contentAt(i));
  //   a.gotoPos({group: 1, atom: 175});
  debugger;
  const bb = a.getListOfPageIndicators();
  debugger;
  const img1 = a.RenderSpecPage({group: 0, atom: 0x317});
  console.log(img1);
  debugger;
  while (a.areWeAtEnd() == false) {
    console.log(a.getCurrentBookIndicator());
    let b = a.renderNextPage();
    debugger;
    // console.log(b);
    console.log(a.getProgress());
    console.log(a.getCurrentBookIndicator())
  }


  // rendererFormatPtr = getRendererFormat(
  //     cWhite, cBlack, cWhite, cBlue, fontSize, fontHeapPtr, font.length);
  // console.log(getFontBuffer(rendererFormatPtr));
  // console.log(getFontBufferLen(rendererFormatPtr));
  // bookbuf = base64ToBuffer(book64);
  // bookheapPtr = copyBufferToHeap(bookbuf);
  // bookPtr = getBookFromBuf(bookheapPtr, bookbuf.length);
  // width = 300;
  // height = 300;
  // bookRendererPtr = getBookRenderer(bookPtr, rendererFormatPtr, width,
  // height); bookIndicatorPtr = initBookIndicator(); firstItem =
  // BookNextPart(bookPtr, bookIndicatorPtr); group_i =
  // getIndicatorPart(firstItem, 0); atom_i = getIndicatorPart(firstItem, 1);
  // NextPage = renderNextPage(bookRendererPtr, firstItem);
  // img = getImageofPageResult(NextPage);
  // imageSize = getDWORDSize(img);
  // pngData = extractFromHeapBytes(imageSize - 4, img + 4);
  // pic = 'data:image/png;base64,' + _arrayBufferToBase64(pngData);
  // console.log(pngData);
}
